var searchData=
[
  ['b',['B',['../struct_b.html',1,'']]],
  ['b_5fhh',['b_hh',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html#a7970ac1436a81aecd15d6c37292df773',1,'torch::nn::detail::RNNImplBase']]],
  ['b_5fih',['b_ih',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html#a8a232debfdd7b96ecc7d4fec5107828c',1,'torch::nn::detail::RNNImplBase']]],
  ['back',['back',['../classc10_1_1_array_ref.html#a13bab03b369684240f26a6629e0b8561',1,'c10::ArrayRef::back()'],['../classtorch_1_1_ordered_dict.html#a92329c8ea28f3017a96fa5bc93e69c28',1,'torch::OrderedDict::back()'],['../classtorch_1_1_ordered_dict.html#acfb461c36291cd734c0e2a81348694b1',1,'torch::OrderedDict::back() const ']]],
  ['backend',['Backend',['../namespacec10.html#ad64cdd76c7657cda0c865ef9e5992fd3',1,'c10']]],
  ['backendgraphinfo',['BackendGraphInfo',['../structcaffe2_1_1onnx_1_1_backend_graph_info.html',1,'caffe2::onnx']]],
  ['backendtransformerbase',['BackendTransformerBase',['../classcaffe2_1_1_backend_transformer_base.html',1,'caffe2']]],
  ['backward',['backward',['../classat_1_1_tensor.html#a93824bce43ce075e789f80a381fc0e2c',1,'at::Tensor::backward(c10::optional&lt; Tensor &gt; gradient=c10::nullopt, bool keep_graph=false, bool create_graph=false)'],['../classat_1_1_tensor.html#ac9b52340543acfa7b2c61ee8d43bd226',1,'at::Tensor::backward(c10::optional&lt; Tensor &gt; gradient=c10::nullopt, bool keep_graph=false, bool create_graph=false)'],['../structtorch_1_1autograd_1_1_variable.html#ad992d756853a851b4b922b76799b270b',1,'torch::autograd::Variable::backward()']]],
  ['bad_5foptional_5faccess',['bad_optional_access',['../classc10_1_1bad__optional__access.html',1,'c10']]],
  ['bar',['Bar',['../classc10__test_1_1_bar.html',1,'c10_test']]],
  ['barrier',['Barrier',['../struct_barrier.html',1,'']]],
  ['base',['base',['../structtorch_1_1autograd_1_1_variable.html#ac120fd3c5d1406867c6ab6f58c5e1cf0',1,'torch::autograd::Variable']]],
  ['base_5f',['base_',['../structtorch_1_1autograd_1_1_variable.html#a417910c5c5305a6815f65ad8b9db0d8d',1,'torch::autograd::Variable']]],
  ['basecontext',['BaseContext',['../classat_1_1_base_context.html',1,'at']]],
  ['baseinputaccessor',['BaseInputAccessor',['../classcaffe2_1_1_base_input_accessor.html',1,'caffe2']]],
  ['basereducer',['BaseReducer',['../classcaffe2_1_1_base_reducer.html',1,'caffe2']]],
  ['basereducergradient',['BaseReducerGradient',['../classcaffe2_1_1_base_reducer_gradient.html',1,'caffe2']]],
  ['basicblock',['BasicBlock',['../classnom_1_1repr_1_1_basic_block.html',1,'nom::repr']]],
  ['batch_5fdata',['batch_data',['../structtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer_1_1_unwrapped_batch_data.html#af5d4dcd58f0d5dbf07388e2518516354',1,'torch::data::datasets::detail::BatchDataBuffer::UnwrappedBatchData']]],
  ['batch_5fqueue_5f',['batch_queue_',['../classtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer.html#ae3737e2b8f5ee1f82ff9b89a44a5bb46',1,'torch::data::datasets::detail::BatchDataBuffer']]],
  ['batch_5fsize_5f',['batch_size_',['../classtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer.html#a359a10757a34ce34120d2dcbd63d56a8',1,'torch::data::datasets::detail::BatchDataBuffer']]],
  ['batchboxcoxop',['BatchBoxCoxOp',['../classcaffe2_1_1_batch_box_cox_op.html',1,'caffe2']]],
  ['batchbucketizeop',['BatchBucketizeOp',['../classcaffe2_1_1_batch_bucketize_op.html',1,'caffe2']]],
  ['batchbucketonehotop',['BatchBucketOneHotOp',['../classcaffe2_1_1_batch_bucket_one_hot_op.html',1,'caffe2']]],
  ['batchdatabuffer',['BatchDataBuffer',['../classtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer.html',1,'torch::data::datasets::detail']]],
  ['batchdataset',['BatchDataset',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20chunkdataset_3c_20chunkreader_2c_20chunksampler_2c_20examplesampler_20_3e_2c_20optional_3c_20chunkreader_3a_3abatchtype_20_3e_2c_20size_5ft_20_3e',['BatchDataset&lt; ChunkDataset&lt; ChunkReader, ChunkSampler, ExampleSampler &gt;, optional&lt; ChunkReader::BatchType &gt;, size_t &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dataset_2c_20size_5ft_20_3e',['BatchDataset&lt; Dataset, size_t &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dummydataset_2c_20std_3a_3avector_3c_20int_20_3e_20_3e',['BatchDataset&lt; DummyDataset, std::vector&lt; int &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dummytensordataset_2c_20std_3a_3avector_3c_20example_3c_20torch_3a_3atensor_2c_20int_20_3e_20_3e_20_3e',['BatchDataset&lt; DummyTensorDataset, std::vector&lt; Example&lt; torch::Tensor, int &gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20mapdataset_3c_20sourcedataset_2c_20appliedtransform_20_3e_2c_20detail_3a_3aoptional_5fif_5ft_3c_20sourcedataset_3a_3ais_5fstateful_2c_20appliedtransform_3a_3aoutputbatchtype_20_3e_2c_20sourcedataset_3a_3abatchrequesttype_20_3e',['BatchDataset&lt; MapDataset&lt; SourceDataset, AppliedTransform &gt;, detail::optional_if_t&lt; SourceDataset::is_stateful, AppliedTransform::OutputBatchType &gt;, SourceDataset::BatchRequestType &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20mnist_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; MNIST, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20self_2c_20optional_3c_20batch_20_3e_2c_20batchrequest_20_3e',['BatchDataset&lt; Self, optional&lt; Batch &gt;, BatchRequest &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20self_2c_20std_3a_3avector_3c_20singleexample_20_3e_20_3e',['BatchDataset&lt; Self, std::vector&lt; SingleExample &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20sharedbatchdataset_3c_20underlyingdataset_20_3e_2c_20underlyingdataset_3a_3abatchtype_2c_20underlyingdataset_3a_3abatchrequesttype_20_3e',['BatchDataset&lt; SharedBatchDataset&lt; UnderlyingDataset &gt;, UnderlyingDataset::BatchType, UnderlyingDataset::BatchRequestType &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20tensordataset_2c_20std_3a_3avector_3c_20tensorexample_20_3e_20_3e',['BatchDataset&lt; TensorDataset, std::vector&lt; TensorExample &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20tensorstringdataset_2c_20std_3a_3avector_3c_20example_3c_20torch_3a_3atensor_2c_20std_3a_3astring_20_3e_20_3e_20_3e',['BatchDataset&lt; TensorStringDataset, std::vector&lt; Example&lt; torch::Tensor, std::string &gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20testindexdataset_2c_20std_3a_3avector_3c_20int_20_3e_2c_20testindex_20_3e',['BatchDataset&lt; TestIndexDataset, std::vector&lt; int &gt;, TestIndex &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20uncopyabledataset_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; UnCopyableDataset, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20uncopyabledataset_2c_20std_3a_3avector_3c_20int_20_3e_20_3e',['BatchDataset&lt; UncopyableDataset, std::vector&lt; int &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20unsizeddataset_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; UnsizedDataset, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdensetosparseop',['BatchDenseToSparseOp',['../classcaffe2_1_1_batch_dense_to_sparse_op.html',1,'caffe2']]],
  ['batchgathergradientop',['BatchGatherGradientOp',['../classcaffe2_1_1_batch_gather_gradient_op.html',1,'caffe2']]],
  ['batchgatherop',['BatchGatherOp',['../classcaffe2_1_1_batch_gather_op.html',1,'caffe2']]],
  ['batchlambda',['BatchLambda',['../classtorch_1_1data_1_1transforms_1_1_batch_lambda.html',1,'torch::data::transforms']]],
  ['batchlambda',['BatchLambda',['../classtorch_1_1data_1_1transforms_1_1_batch_lambda.html#adbfa3c8d6ab4c848a694d476c31db4da',1,'torch::data::transforms::BatchLambda']]],
  ['batchmatmuldnnlowpop',['BatchMatMulDNNLowPOp',['../classcaffe2_1_1_batch_mat_mul_d_n_n_low_p_op.html',1,'caffe2']]],
  ['batchmatmulop',['BatchMatMulOp',['../classcaffe2_1_1_batch_mat_mul_op.html',1,'caffe2']]],
  ['batchmomentsgradientop',['BatchMomentsGradientOp',['../classcaffe2_1_1_batch_moments_gradient_op.html',1,'caffe2']]],
  ['batchmomentsop',['BatchMomentsOp',['../classcaffe2_1_1_batch_moments_op.html',1,'caffe2']]],
  ['batchnormalization',['BatchNormalization',['../class_batch_normalization.html',1,'']]],
  ['batchnormimpl',['BatchNormImpl',['../classtorch_1_1nn_1_1_batch_norm_impl.html',1,'torch::nn']]],
  ['batchnormoptions',['BatchNormOptions',['../structtorch_1_1nn_1_1_batch_norm_options.html',1,'torch::nn']]],
  ['batchonehotop',['BatchOneHotOp',['../classcaffe2_1_1_batch_one_hot_op.html',1,'caffe2']]],
  ['batchpermutationdnnlowpop',['BatchPermutationDNNLowPOp',['../classcaffe2_1_1_batch_permutation_d_n_n_low_p_op.html',1,'caffe2']]],
  ['batchpermutationgradientop',['BatchPermutationGradientOp',['../classcaffe2_1_1_batch_permutation_gradient_op.html',1,'caffe2']]],
  ['batchpermutationop',['BatchPermutationOp',['../classcaffe2_1_1_batch_permutation_op.html',1,'caffe2']]],
  ['batchsize',['BatchSize',['../structtorch_1_1data_1_1samplers_1_1_batch_size.html',1,'torch::data::samplers']]],
  ['batchsparsetodenseop',['BatchSparseToDenseOp',['../classcaffe2_1_1_batch_sparse_to_dense_op.html',1,'caffe2']]],
  ['batchtensor',['BatchTensor',['../structtorch_1_1jit_1_1_batch_tensor.html',1,'torch::jit']]],
  ['batchtospaceop',['BatchToSpaceOp',['../classcaffe2_1_1_batch_to_space_op.html',1,'caffe2']]],
  ['batchtransform',['BatchTransform',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20input_2c_20output_20_3e',['BatchTransform&lt; Input, Output &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20std_3a_3avector_3c_20example_3c_20tensor_2c_20target_20_3e_20_3e_2c_20std_3a_3avector_3c_20example_3c_20tensor_2c_20target_20_3e_20_3e_20_3e',['BatchTransform&lt; std::vector&lt; Example&lt; Tensor, Target &gt; &gt;, std::vector&lt; Example&lt; Tensor, Target &gt; &gt; &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20std_3a_3avector_3c_20input_20_3e_2c_20std_3a_3avector_3c_20output_20_3e_20_3e',['BatchTransform&lt; std::vector&lt; Input &gt;, std::vector&lt; Output &gt; &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['bboxtransformop',['BBoxTransformOp',['../classcaffe2_1_1_b_box_transform_op.html',1,'caffe2']]],
  ['begin',['begin',['../classtorch_1_1data_1_1_data_loader_base.html#a9a932b57ca185a126b4054321d52c40f',1,'torch::data::DataLoaderBase::begin()'],['../classtorch_1_1nn_1_1_sequential_impl.html#a499ba7d0b1739ca9f05ca7cdadd21885',1,'torch::nn::SequentialImpl::begin()'],['../classtorch_1_1nn_1_1_sequential_impl.html#a8060bcde842681a14d7248ffa4a287ea',1,'torch::nn::SequentialImpl::begin() const '],['../classtorch_1_1_ordered_dict.html#a8ead9f7ababc1b577207e42005448254',1,'torch::OrderedDict::begin()'],['../classtorch_1_1_ordered_dict.html#a959015c8a943ad60e30951c4e18ecec6',1,'torch::OrderedDict::begin() const ']]],
  ['benchmarkparam',['BenchmarkParam',['../structcaffe2_1_1emulator_1_1_benchmark_param.html',1,'caffe2::emulator']]],
  ['benchmarkrunner',['BenchmarkRunner',['../classcaffe2_1_1emulator_1_1_benchmark_runner.html',1,'caffe2::emulator']]],
  ['bernoullijsdgradientop',['BernoulliJSDGradientOp',['../classcaffe2_1_1_bernoulli_j_s_d_gradient_op.html',1,'caffe2']]],
  ['bernoullijsdop',['BernoulliJSDOp',['../classcaffe2_1_1_bernoulli_j_s_d_op.html',1,'caffe2']]],
  ['bias',['bias',['../classtorch_1_1nn_1_1_batch_norm_impl.html#ab95f94b27f435d9a454758a7edddf72e',1,'torch::nn::BatchNormImpl::bias()'],['../classtorch_1_1nn_1_1_conv_impl.html#aa99bb4612ebf8072a23b4a0107cbcf9b',1,'torch::nn::ConvImpl::bias()'],['../classtorch_1_1nn_1_1_linear_impl.html#a7d39a66f790f08175f572af8b023a4fd',1,'torch::nn::LinearImpl::bias()']]],
  ['binary_5ffunction_5ftraits',['binary_function_traits',['../structbinary__function__traits.html',1,'']]],
  ['binaryelementwisednnlowpop',['BinaryElementwiseDNNLowPOp',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisednnlowpop_3c_20t_2c_20addfp32op_20_3e',['BinaryElementwiseDNNLowPOp&lt; T, AddFp32Op &gt;',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisednnlowpop_3c_20t_2c_20mulfp32op_20_3e',['BinaryElementwiseDNNLowPOp&lt; T, MulFp32Op &gt;',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisewithargsgradientop',['BinaryElementwiseWithArgsGradientOp',['../classcaffe2_1_1_binary_elementwise_with_args_gradient_op.html',1,'caffe2']]],
  ['binaryelementwisewithargsgradientop_3c_20numerictypes_2c_20cpucontext_2c_20binaryfunctorwithdefaultctor_3c_20divfunctor_3c_20cpucontext_20_3e_20_3e_2c_20sametypeasinput_2c_20sametypeasinput_20_3e',['BinaryElementwiseWithArgsGradientOp&lt; NumericTypes, CPUContext, BinaryFunctorWithDefaultCtor&lt; DivFunctor&lt; CPUContext &gt; &gt;, SameTypeAsInput, SameTypeAsInput &gt;',['../classcaffe2_1_1_binary_elementwise_with_args_gradient_op_3_01_numeric_types_00_01_c_p_u_context_18719035c30b9048fc92376cf087945e.html',1,'caffe2']]],
  ['binaryelementwisewithargsop',['BinaryElementwiseWithArgsOp',['../classcaffe2_1_1_binary_elementwise_with_args_op.html',1,'caffe2']]],
  ['binaryfunctorwithdefaultctor',['BinaryFunctorWithDefaultCtor',['../structcaffe2_1_1_binary_functor_with_default_ctor.html',1,'caffe2']]],
  ['binaryfunctorwithdefaultctor_3c_20caffe2_3a_3adivfunctor_3c_20caffe2_3a_3acpucontext_20_3e_20_3e',['BinaryFunctorWithDefaultCtor&lt; caffe2::DivFunctor&lt; caffe2::CPUContext &gt; &gt;',['../structcaffe2_1_1_binary_functor_with_default_ctor.html',1,'caffe2']]],
  ['binop',['BinOp',['../structtorch_1_1jit_1_1script_1_1_bin_op.html',1,'torch::jit::script']]],
  ['bisectpercentileop',['BisectPercentileOp',['../classcaffe2_1_1_bisect_percentile_op.html',1,'caffe2']]],
  ['bits',['bits',['../struct_d_l_data_type.html#a412e36fa9c58e808a2333e9044c5d9b5',1,'DLDataType']]],
  ['blob',['Blob',['../classcaffe2_1_1_blob.html',1,'caffe2']]],
  ['blob',['Blob',['../classcaffe2_1_1_blob.html#aa81888495404bbe2ff12e6391121280d',1,'caffe2::Blob']]],
  ['blobdeserializerbase',['BlobDeserializerBase',['../classcaffe2_1_1_blob_deserializer_base.html',1,'caffe2']]],
  ['blobs',['Blobs',['../classcaffe2_1_1_workspace.html#abbff5b6bd7b8634954963e167e9e6e7a',1,'caffe2::Workspace']]],
  ['blobserializerbase',['BlobSerializerBase',['../classcaffe2_1_1_blob_serializer_base.html',1,'caffe2']]],
  ['blobsqueue',['BlobsQueue',['../classcaffe2_1_1_blobs_queue.html',1,'caffe2']]],
  ['blobsqueuedb',['BlobsQueueDB',['../classcaffe2_1_1db_1_1_blobs_queue_d_b.html',1,'caffe2::db']]],
  ['blobsqueuedbcursor',['BlobsQueueDBCursor',['../classcaffe2_1_1db_1_1_blobs_queue_d_b_cursor.html',1,'caffe2::db']]],
  ['blobstatgetter',['BlobStatGetter',['../structcaffe2_1_1_blob_stat_getter.html',1,'caffe2']]],
  ['blobstatregistry',['BlobStatRegistry',['../structcaffe2_1_1_blob_stat_registry.html',1,'caffe2']]],
  ['block',['Block',['../structtorch_1_1jit_1_1_block.html',1,'torch::jit']]],
  ['blockingcounter',['BlockingCounter',['../classcaffe2_1_1_blocking_counter.html',1,'caffe2']]],
  ['booleandispatchvalue',['BooleanDispatchValue',['../structtorch_1_1jit_1_1script_1_1_boolean_dispatch_value.html',1,'torch::jit::script']]],
  ['booleanmaskop',['BooleanMaskOp',['../classcaffe2_1_1_boolean_mask_op.html',1,'caffe2']]],
  ['booleanunmaskop',['BooleanUnmaskOp',['../classcaffe2_1_1_boolean_unmask_op.html',1,'caffe2']]],
  ['boolinfo',['BoolInfo',['../structtorch_1_1jit_1_1script_1_1_bool_info.html',1,'torch::jit::script']]],
  ['booltype',['BoolType',['../structc10_1_1_bool_type.html',1,'c10']]],
  ['boundshapeinferencer',['BoundShapeInferencer',['../classcaffe2_1_1_bound_shape_inferencer.html',1,'caffe2']]],
  ['boundshapespec',['BoundShapeSpec',['../structcaffe2_1_1_bound_shape_spec.html',1,'caffe2']]],
  ['boxwithnmslimitop',['BoxWithNMSLimitOp',['../classcaffe2_1_1_box_with_n_m_s_limit_op.html',1,'caffe2']]],
  ['branch',['Branch',['../classnom_1_1repr_1_1_branch.html',1,'nom::repr']]],
  ['brgnchwctopackedint8bgrastylizerdeprocessop',['BRGNCHWCToPackedInt8BGRAStylizerDeprocessOp',['../classcaffe2_1_1_b_r_g_n_c_h_w_c_to_packed_int8_b_g_r_a_stylizer_deprocess_op.html',1,'caffe2']]],
  ['broadcastnccltest',['BroadcastNCCLTest',['../class_broadcast_n_c_c_l_test.html',1,'']]],
  ['buffer',['buffer',['../structtorch_1_1data_1_1detail_1_1sequencers_1_1_ordered_sequencer.html#a9132ec17a6ff3ead93bee493cc8ce3a4',1,'torch::data::detail::sequencers::OrderedSequencer']]],
  ['buffer_5f',['buffer_',['../structtorch_1_1data_1_1detail_1_1sequencers_1_1_ordered_sequencer.html#abf1cf8d5bb80089ae24fbe3468b16eed',1,'torch::data::detail::sequencers::OrderedSequencer']]],
  ['buffer_5fat',['buffer_at',['../classtorch_1_1optim_1_1detail_1_1_optimizer_base.html#ab06dc3430b1d8bd15f840670b2798449',1,'torch::optim::detail::OptimizerBase::buffer_at(std::vector&lt; T &gt; &amp;buffers, size_t index)'],['../classtorch_1_1optim_1_1detail_1_1_optimizer_base.html#a2844f4aa01f3023d418f4fe63d6d3da2',1,'torch::optim::detail::OptimizerBase::buffer_at(std::vector&lt; Tensor &gt; &amp;buffers, size_t index)']]],
  ['bufferedtokenizer',['BufferedTokenizer',['../classcaffe2_1_1_buffered_tokenizer.html',1,'caffe2']]],
  ['buffers',['buffers',['../classtorch_1_1nn_1_1_module.html#a92cc52f55f49f84f9d2b277ff4816c95',1,'torch::nn::Module']]],
  ['buffertestmodule',['BufferTestModule',['../struct_buffer_test_module.html',1,'']]],
  ['bug_20list',['Bug List',['../bug.html',1,'']]],
  ['builder',['Builder',['../structat_1_1_tensor_iterator_1_1_builder.html',1,'at::TensorIterator']]],
  ['builtinfunction',['BuiltinFunction',['../structtorch_1_1jit_1_1script_1_1_builtin_function.html',1,'torch::jit::script']]],
  ['builtinfunctionregistry',['BuiltinFunctionRegistry',['../structtorch_1_1jit_1_1script_1_1_builtin_function_registry.html',1,'torch::jit::script']]],
  ['builtinmodule',['BuiltinModule',['../structtorch_1_1jit_1_1script_1_1_builtin_module.html',1,'torch::jit::script']]],
  ['bump_5fversion',['bump_version',['../structtorch_1_1autograd_1_1_variable.html#aa7a0fe2af7bc682b483bc30d723ec176',1,'torch::autograd::Variable']]],
  ['byte_5foffset',['byte_offset',['../struct_d_l_tensor.html#a647dfbb2a3b976c4e9d1e17740dca568',1,'DLTensor']]],
  ['byteweightdequantop',['ByteWeightDequantOp',['../classcaffe2_1_1_byte_weight_dequant_op.html',1,'caffe2']]]
];
