var searchData=
[
  ['unary_5ffunction_5ftraits',['unary_function_traits',['../structunary__function__traits.html',1,'']]],
  ['unaryelementwisewithargsdnnlowpop',['UnaryElementwiseWithArgsDNNLowPOp',['../classcaffe2_1_1_unary_elementwise_with_args_d_n_n_low_p_op.html',1,'caffe2']]],
  ['unaryelementwisewithargsop',['UnaryElementwiseWithArgsOp',['../classcaffe2_1_1_unary_elementwise_with_args_op.html',1,'caffe2']]],
  ['unaryfunctorwithdefaultctor',['UnaryFunctorWithDefaultCtor',['../structcaffe2_1_1_unary_functor_with_default_ctor.html',1,'caffe2']]],
  ['unaryop',['UnaryOp',['../structtorch_1_1jit_1_1script_1_1_unary_op.html',1,'torch::jit::script']]],
  ['uncopyabledataset',['UncopyableDataset',['../struct_uncopyable_dataset.html',1,'UncopyableDataset'],['../struct_un_copyable_dataset.html',1,'UnCopyableDataset']]],
  ['undefinedtensorimpl',['UndefinedTensorImpl',['../structc10_1_1_undefined_tensor_impl.html',1,'c10']]],
  ['undefinedtype',['UndefinedType',['../structat_1_1_undefined_type.html',1,'at']]],
  ['uniformfillop',['UniformFillOp',['../classcaffe2_1_1_uniform_fill_op.html',1,'caffe2']]],
  ['unique_5ftype_5fchecker',['unique_type_checker',['../structtorch_1_1cuda_1_1unique__type__checker.html',1,'torch::cuda']]],
  ['unique_5ftype_5ffor',['unique_type_for',['../structtorch_1_1unique__type__for.html',1,'torch']]],
  ['unique_5ftype_5ffor_3c_20t_5b_5d_3e',['unique_type_for&lt; T[]&gt;',['../structtorch_1_1unique__type__for_3_01_t[]_4.html',1,'torch']]],
  ['unique_5ftype_5ffor_3c_20t_5bn_5d_3e',['unique_type_for&lt; T[N]&gt;',['../structtorch_1_1unique__type__for_3_01_t[_n]_4.html',1,'torch']]],
  ['uniqueop',['UniqueOp',['../classcaffe2_1_1_unique_op.html',1,'caffe2']]],
  ['uniqueuniformfillop',['UniqueUniformFillOp',['../classcaffe2_1_1_unique_uniform_fill_op.html',1,'caffe2']]],
  ['uniquevoidptr',['UniqueVoidPtr',['../classc10_1_1detail_1_1_unique_void_ptr.html',1,'c10::detail']]],
  ['unpackedinput',['UnpackedInput',['../struct_unpacked_input.html',1,'']]],
  ['unpacksegmentsop',['UnpackSegmentsOp',['../classcaffe2_1_1_unpack_segments_op.html',1,'caffe2']]],
  ['unpickler',['Unpickler',['../classtorch_1_1jit_1_1_unpickler.html',1,'torch::jit']]],
  ['unsizeddataset',['UnsizedDataset',['../struct_unsized_dataset.html',1,'']]],
  ['unsupportedoperatorfeature',['UnsupportedOperatorFeature',['../classcaffe2_1_1_unsupported_operator_feature.html',1,'caffe2']]],
  ['unwrappedbatchdata',['UnwrappedBatchData',['../structtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer_1_1_unwrapped_batch_data.html',1,'torch::data::datasets::detail::BatchDataBuffer']]],
  ['upsamplebilineargradientop',['UpsampleBilinearGradientOp',['../classcaffe2_1_1_upsample_bilinear_gradient_op.html',1,'caffe2']]],
  ['upsamplebilinearop',['UpsampleBilinearOp',['../classcaffe2_1_1_upsample_bilinear_op.html',1,'caffe2']]],
  ['upsamplenearestgradientop',['UpsampleNearestGradientOp',['../classcaffe2_1_1_upsample_nearest_gradient_op.html',1,'caffe2']]],
  ['upsamplenearestop',['UpsampleNearestOp',['../classcaffe2_1_1_upsample_nearest_op.html',1,'caffe2']]],
  ['use',['Use',['../structtorch_1_1jit_1_1_use.html',1,'torch::jit']]],
  ['uselist',['UseList',['../structtorch_1_1jit_1_1_use_list.html',1,'torch::jit']]]
];
