var searchData=
[
  ['d',['D',['../struct_d.html',1,'']]],
  ['data',['Data',['../classnom_1_1repr_1_1_data.html',1,'nom::repr']]],
  ['datacoupleop',['DataCoupleOp',['../classcaffe2_1_1_data_couple_op.html',1,'caffe2']]],
  ['dataflowtestgraph',['DataFlowTestGraph',['../structnom_1_1matcher_1_1_data_flow_test_graph.html',1,'nom::matcher']]],
  ['dataflowtestgraphcriteria',['DataFlowTestGraphCriteria',['../structnom_1_1matcher_1_1_data_flow_test_graph_criteria.html',1,'nom::matcher']]],
  ['dataloaderbase',['DataLoaderBase',['../classtorch_1_1data_1_1_data_loader_base.html',1,'torch::data']]],
  ['dataloaderbase_3c_20dataset_2c_20dataset_3a_3abatchtype_2c_20sampler_3a_3abatchrequesttype_20_3e',['DataLoaderBase&lt; Dataset, Dataset::BatchType, Sampler::BatchRequestType &gt;',['../classtorch_1_1data_1_1_data_loader_base.html',1,'torch::data']]],
  ['dataloaderbase_3c_20dataset_2c_20dataset_3a_3abatchtype_3a_3avalue_5ftype_2c_20dataset_3a_3abatchrequesttype_20_3e',['DataLoaderBase&lt; Dataset, Dataset::BatchType::value_type, Dataset::BatchRequestType &gt;',['../classtorch_1_1data_1_1_data_loader_base.html',1,'torch::data']]],
  ['dataloaderoptions',['DataLoaderOptions',['../structtorch_1_1data_1_1_data_loader_options.html',1,'torch::data']]],
  ['datanetfiller',['DataNetFiller',['../classcaffe2_1_1emulator_1_1_data_net_filler.html',1,'caffe2::emulator']]],
  ['dataptr',['DataPtr',['../classc10_1_1_data_ptr.html',1,'c10']]],
  ['datarandomfiller',['DataRandomFiller',['../classcaffe2_1_1emulator_1_1_data_random_filler.html',1,'caffe2::emulator']]],
  ['dataset',['Dataset',['../structordering__test_1_1_dataset.html',1,'ordering_test']]],
  ['dataset',['Dataset',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20dummydataset_2c_20int_20_3e',['Dataset&lt; DummyDataset, int &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20dummytensordataset_2c_20example_3c_20torch_3a_3atensor_2c_20int_20_3e_20_3e',['Dataset&lt; DummyTensorDataset, Example&lt; torch::Tensor, int &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20mnist_20_3e',['Dataset&lt; MNIST &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20tensordataset_2c_20tensorexample_20_3e',['Dataset&lt; TensorDataset, TensorExample &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20tensorstringdataset_2c_20example_3c_20torch_3a_3atensor_2c_20std_3a_3astring_20_3e_20_3e',['Dataset&lt; TensorStringDataset, Example&lt; torch::Tensor, std::string &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20uncopyabledataset_20_3e',['Dataset&lt; UnCopyableDataset &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20uncopyabledataset_2c_20int_20_3e',['Dataset&lt; UncopyableDataset, int &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['dataset_3c_20unsizeddataset_20_3e',['Dataset&lt; UnsizedDataset &gt;',['../classtorch_1_1data_1_1datasets_1_1_dataset.html',1,'torch::data::datasets']]],
  ['datashuttle',['DataShuttle',['../classtorch_1_1data_1_1detail_1_1_data_shuttle.html',1,'torch::data::detail']]],
  ['datashuttle_3c_20torch_3a_3adata_3a_3adataloaderbase_3a_3ajob_2c_20torch_3a_3adata_3a_3adataloaderbase_3a_3aresult_20_3e',['DataShuttle&lt; torch::data::DataLoaderBase::Job, torch::data::DataLoaderBase::Result &gt;',['../classtorch_1_1data_1_1detail_1_1_data_shuttle.html',1,'torch::data::detail']]],
  ['db',['DB',['../classcaffe2_1_1db_1_1_d_b.html',1,'caffe2::db']]],
  ['dbexistsop',['DBExistsOp',['../classcaffe2_1_1_d_b_exists_op.html',1,'caffe2']]],
  ['dbreader',['DBReader',['../classcaffe2_1_1db_1_1_d_b_reader.html',1,'caffe2::db']]],
  ['dbreaderdeserializer',['DBReaderDeserializer',['../classcaffe2_1_1db_1_1_d_b_reader_deserializer.html',1,'caffe2::db']]],
  ['dbreaderserializer',['DBReaderSerializer',['../classcaffe2_1_1db_1_1_d_b_reader_serializer.html',1,'caffe2::db']]],
  ['deadcodeeliminator',['DeadCodeEliminator',['../classtorch_1_1jit_1_1_dead_code_eliminator.html',1,'torch::jit']]],
  ['decl',['Decl',['../structtorch_1_1jit_1_1script_1_1_decl.html',1,'torch::jit::script']]],
  ['declare',['Declare',['../class_declare.html',1,'']]],
  ['decodedframe',['DecodedFrame',['../classcaffe2_1_1_decoded_frame.html',1,'caffe2']]],
  ['decref',['Decref',['../struct_decref.html',1,'']]],
  ['def',['Def',['../structtorch_1_1jit_1_1script_1_1_def.html',1,'torch::jit::script']]],
  ['defaultcpuallocator',['DefaultCPUAllocator',['../structc10_1_1_default_c_p_u_allocator.html',1,'c10']]],
  ['defaultdtypetest',['DefaultDtypeTest',['../struct_default_dtype_test.html',1,'']]],
  ['defaultengine',['DefaultEngine',['../classcaffe2_1_1_default_engine.html',1,'caffe2']]],
  ['defaultfunctiontype',['DefaultFunctionType',['../structtorch_1_1autograd_1_1_default_function_type.html',1,'torch::autograd']]],
  ['defaultptrtraits',['DefaultPtrTraits',['../structat_1_1_default_ptr_traits.html',1,'at']]],
  ['defaulttensoroptions',['DefaultTensorOptions',['../structc10_1_1_default_tensor_options.html',1,'c10']]],
  ['defcontext',['DefContext',['../structtorch_1_1jit_1_1script_1_1_def_context.html',1,'torch::jit::script']]],
  ['deformconvgradientop',['DeformConvGradientOp',['../classcaffe2_1_1_deform_conv_gradient_op.html',1,'caffe2']]],
  ['deformconvop',['DeformConvOp',['../classcaffe2_1_1_deform_conv_op.html',1,'caffe2']]],
  ['deformconvopbase',['DeformConvOpBase',['../classcaffe2_1_1_deform_conv_op_base.html',1,'caffe2']]],
  ['delayederror',['DelayedError',['../structtorch_1_1autograd_1_1_delayed_error.html',1,'torch::autograd']]],
  ['delayederrorctor',['DelayedErrorCtor',['../struct_delayed_error_ctor.html',1,'']]],
  ['densevectortoidlistop',['DenseVectorToIdListOp',['../classcaffe2_1_1_dense_vector_to_id_list_op.html',1,'caffe2']]],
  ['dequantizednnlowpop',['DequantizeDNNLowPOp',['../classcaffe2_1_1_dequantize_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dequeueblobsop',['DequeueBlobsOp',['../classcaffe2_1_1_dequeue_blobs_op.html',1,'caffe2']]],
  ['dequeuerebatchingqueueop',['DequeueRebatchingQueueOp',['../classcaffe2_1_1_dequeue_rebatching_queue_op.html',1,'caffe2']]],
  ['descriptor',['Descriptor',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnnconvolutionstruct_2c_26cudnncreateconvolutiondescriptor_2c_26cudnndestroyconvolutiondescriptor_20_3e',['Descriptor&lt; cudnnConvolutionStruct,&amp;cudnnCreateConvolutionDescriptor,&amp;cudnnDestroyConvolutionDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnnctclossstruct_2c_26cudnncreatectclossdescriptor_2c_26cudnndestroyctclossdescriptor_20_3e',['Descriptor&lt; cudnnCTCLossStruct,&amp;cudnnCreateCTCLossDescriptor,&amp;cudnnDestroyCTCLossDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnndropoutstruct_2c_26cudnncreatedropoutdescriptor_2c_26cudnndestroydropoutdescriptor_20_3e',['Descriptor&lt; cudnnDropoutStruct,&amp;cudnnCreateDropoutDescriptor,&amp;cudnnDestroyDropoutDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnnfilterstruct_2c_26cudnncreatefilterdescriptor_2c_26cudnndestroyfilterdescriptor_20_3e',['Descriptor&lt; cudnnFilterStruct,&amp;cudnnCreateFilterDescriptor,&amp;cudnnDestroyFilterDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnnrnnstruct_2c_26cudnncreaternndescriptor_2c_26cudnndestroyrnndescriptor_20_3e',['Descriptor&lt; cudnnRNNStruct,&amp;cudnnCreateRNNDescriptor,&amp;cudnnDestroyRNNDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnnspatialtransformerstruct_2c_26cudnncreatespatialtransformerdescriptor_2c_26cudnndestroyspatialtransformerdescriptor_20_3e',['Descriptor&lt; cudnnSpatialTransformerStruct,&amp;cudnnCreateSpatialTransformerDescriptor,&amp;cudnnDestroySpatialTransformerDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20cudnntensorstruct_2c_26cudnncreatetensordescriptor_2c_26cudnndestroytensordescriptor_20_3e',['Descriptor&lt; cudnnTensorStruct,&amp;cudnnCreateTensorDescriptor,&amp;cudnnDestroyTensorDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20miopenconvolutiondescriptor_2c_26miopencreateconvolutiondescriptor_2c_26miopendestroyconvolutiondescriptor_20_3e',['Descriptor&lt; miopenConvolutionDescriptor,&amp;miopenCreateConvolutionDescriptor,&amp;miopenDestroyConvolutionDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptor_3c_20miopentensordescriptor_2c_26miopencreatetensordescriptor_2c_26miopendestroytensordescriptor_20_3e',['Descriptor&lt; miopenTensorDescriptor,&amp;miopenCreateTensorDescriptor,&amp;miopenDestroyTensorDescriptor &gt;',['../classat_1_1native_1_1_descriptor.html',1,'at::native']]],
  ['descriptordeleter',['DescriptorDeleter',['../structat_1_1native_1_1_descriptor_deleter.html',1,'at::native']]],
  ['detailedexportedstat',['DetailedExportedStat',['../classcaffe2_1_1_detailed_exported_stat.html',1,'caffe2']]],
  ['device',['Device',['../structcaffe2_1_1onnx_1_1_device.html',1,'caffe2::onnx']]],
  ['device',['Device',['../structc10_1_1_device.html',1,'c10']]],
  ['deviceguard',['DeviceGuard',['../classc10_1_1_device_guard.html',1,'c10']]],
  ['deviceguardimplinterface',['DeviceGuardImplInterface',['../structc10_1_1impl_1_1_device_guard_impl_interface.html',1,'c10::impl']]],
  ['deviceguardimplregistrar',['DeviceGuardImplRegistrar',['../classc10_1_1impl_1_1_device_guard_impl_registrar.html',1,'c10::impl']]],
  ['deviceobjtype',['DeviceObjType',['../structc10_1_1_device_obj_type.html',1,'c10']]],
  ['devicetyperegisterer',['DeviceTypeRegisterer',['../structcaffe2_1_1_device_type_registerer.html',1,'caffe2']]],
  ['dftidescriptor',['DftiDescriptor',['../classat_1_1native_1_1_dfti_descriptor.html',1,'at::native']]],
  ['dftidescriptordeleter',['DftiDescriptorDeleter',['../structat_1_1native_1_1_dfti_descriptor_deleter.html',1,'at::native']]],
  ['diagonalfillop',['DiagonalFillOp',['../classcaffe2_1_1_diagonal_fill_op.html',1,'caffe2']]],
  ['dictequalto',['DictEqualTo',['../structc10_1_1ivalue_1_1_dict_equal_to.html',1,'c10::ivalue']]],
  ['dicthash',['DictHash',['../structc10_1_1ivalue_1_1_dict_hash.html',1,'c10::ivalue']]],
  ['dictliteral',['DictLiteral',['../structtorch_1_1jit_1_1script_1_1_dict_literal.html',1,'torch::jit::script']]],
  ['dicttype',['DictType',['../structc10_1_1_dict_type.html',1,'c10']]],
  ['dimcounter',['DimCounter',['../structat_1_1_dim_counter.html',1,'at']]],
  ['dimensionedtensortype',['DimensionedTensorType',['../structc10_1_1_dimensioned_tensor_type.html',1,'c10']]],
  ['disjunction',['disjunction',['../structc10_1_1guts_1_1disjunction.html',1,'c10::guts']]],
  ['disjunction_3c_20b1_20_3e',['disjunction&lt; B1 &gt;',['../structc10_1_1guts_1_1disjunction_3_01_b1_01_4.html',1,'c10::guts']]],
  ['disjunction_3c_20b1_2c_20bn_2e_2e_2e_20_3e',['disjunction&lt; B1, Bn... &gt;',['../structc10_1_1guts_1_1disjunction_3_01_b1_00_01_bn_8_8_8_01_4.html',1,'c10::guts']]],
  ['dispatcher',['Dispatcher',['../classc10_1_1_dispatcher.html',1,'c10']]],
  ['dispatchhelper',['DispatchHelper',['../structcaffe2_1_1_dispatch_helper.html',1,'caffe2']]],
  ['dispatchhelper_3c_20fixedvalues_3c_20firstval_2c_20values_2e_2e_2e_20_3e_2c_20extraargs_2e_2e_2e_20_3e',['DispatchHelper&lt; FixedValues&lt; FirstVal, Values... &gt;, ExtraArgs... &gt;',['../structcaffe2_1_1_dispatch_helper_3_01_fixed_values_3_01_first_val_00_01_values_8_8_8_01_4_00_01_extra_args_8_8_8_01_4.html',1,'caffe2']]],
  ['dispatchhelper_3c_20fixedvalues_3c_3e_2c_20extraargs_2e_2e_2e_20_3e',['DispatchHelper&lt; FixedValues&lt;&gt;, ExtraArgs... &gt;',['../structcaffe2_1_1_dispatch_helper_3_01_fixed_values_3_4_00_01_extra_args_8_8_8_01_4.html',1,'caffe2']]],
  ['dispatchstub_3c_20rt_28_2a_29_28args_2e_2e_2e_29_2c_20t_20_3e',['DispatchStub&lt; rT(*)(Args...), T &gt;',['../structat_1_1native_1_1_dispatch_stub_3_01r_t_07_5_08_07_args_8_8_8_08_00_01_t_01_4.html',1,'at::native']]],
  ['dispatchtable',['DispatchTable',['../classc10_1_1_dispatch_table.html',1,'c10']]],
  ['dispatchtableentry',['DispatchTableEntry',['../structc10_1_1_dispatch_table_entry.html',1,'c10']]],
  ['distributedrandomsampler',['DistributedRandomSampler',['../classtorch_1_1data_1_1samplers_1_1_distributed_random_sampler.html',1,'torch::data::samplers']]],
  ['distributedsampler',['DistributedSampler',['../classtorch_1_1data_1_1samplers_1_1_distributed_sampler.html',1,'torch::data::samplers']]],
  ['distributedsampler_3c_3e',['DistributedSampler&lt;&gt;',['../classtorch_1_1data_1_1samplers_1_1_distributed_sampler.html',1,'torch::data::samplers']]],
  ['distributedsequentialsampler',['DistributedSequentialSampler',['../classtorch_1_1data_1_1samplers_1_1_distributed_sequential_sampler.html',1,'torch::data::samplers']]],
  ['divfunctor',['DivFunctor',['../structcaffe2_1_1_div_functor.html',1,'caffe2']]],
  ['divfunctor_3c_20caffe2_3a_3acpucontext_20_3e',['DivFunctor&lt; caffe2::CPUContext &gt;',['../structcaffe2_1_1_div_functor.html',1,'caffe2']]],
  ['dlcontext',['DLContext',['../struct_d_l_context.html',1,'']]],
  ['dldatatype',['DLDataType',['../struct_d_l_data_type.html',1,'']]],
  ['dlmanagedtensor',['DLManagedTensor',['../struct_d_l_managed_tensor.html',1,'']]],
  ['dlnnapi',['dlnnapi',['../structdlnnapi.html',1,'']]],
  ['dltensor',['DLTensor',['../struct_d_l_tensor.html',1,'']]],
  ['dnnlowpop',['DNNLowPOp',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20std_3a_3auint8_5ft_2c_20fcfp32op_20_3e',['DNNLowPOp&lt; std::uint8_t, FCFp32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20std_3a_3auint8_5ft_2c_20fullyconnectedop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; std::uint8_t, FullyConnectedOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20addfp32op_20_3e',['DNNLowPOp&lt; T, AddFp32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20batchmatmulop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, BatchMatMulOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20batchpermutationfp32op_20_3e',['DNNLowPOp&lt; T, BatchPermutationFP32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20channelshufflefp32op_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, ChannelShuffleFp32Op&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20concatop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, ConcatOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20elementwiselinearfp32op_20_3e',['DNNLowPOp&lt; T, ElementwiseLinearFp32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20fullyconnectedop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, FullyConnectedOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20groupnormfp32op_20_3e',['DNNLowPOp&lt; T, GroupNormFP32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20mulfp32op_20_3e',['DNNLowPOp&lt; T, MulFp32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20resizenearestfp32op_20_3e',['DNNLowPOp&lt; T, ResizeNearestFP32Op &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20spatialbnop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, SpatialBNOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['dnnlowpop_3c_20t_2c_20sumop_3c_20cpucontext_20_3e_20_3e',['DNNLowPOp&lt; T, SumOp&lt; CPUContext &gt; &gt;',['../classcaffe2_1_1_d_n_n_low_p_op.html',1,'caffe2']]],
  ['doop',['DoOp',['../classcaffe2_1_1_do_op.html',1,'caffe2']]],
  ['dotgenerator',['DotGenerator',['../classnom_1_1converters_1_1_dot_generator.html',1,'nom::converters']]],
  ['dotproductgradientop',['DotProductGradientOp',['../classcaffe2_1_1_dot_product_gradient_op.html',1,'caffe2']]],
  ['dotproductop',['DotProductOp',['../classcaffe2_1_1_dot_product_op.html',1,'caffe2']]],
  ['dotproductwithpaddinggradientop',['DotProductWithPaddingGradientOp',['../classcaffe2_1_1_dot_product_with_padding_gradient_op.html',1,'caffe2']]],
  ['dotproductwithpaddingop',['DotProductWithPaddingOp',['../classcaffe2_1_1_dot_product_with_padding_op.html',1,'caffe2']]],
  ['doubler',['Doubler',['../struct_doubler.html',1,'']]],
  ['dropoutdescriptor',['DropoutDescriptor',['../structat_1_1native_1_1_dropout_descriptor.html',1,'at::native']]],
  ['dropoutgradientop',['DropoutGradientOp',['../classcaffe2_1_1_dropout_gradient_op.html',1,'caffe2']]],
  ['dropoutimpl',['DropoutImpl',['../classtorch_1_1nn_1_1_dropout_impl.html',1,'torch::nn']]],
  ['dropoutimplbase',['DropoutImplBase',['../classtorch_1_1nn_1_1detail_1_1_dropout_impl_base.html',1,'torch::nn::detail']]],
  ['dropoutimplbase_3c_20dropoutimpl_20_3e',['DropoutImplBase&lt; DropoutImpl &gt;',['../classtorch_1_1nn_1_1detail_1_1_dropout_impl_base.html',1,'torch::nn::detail']]],
  ['dropoutimplbase_3c_20featuredropoutimpl_20_3e',['DropoutImplBase&lt; FeatureDropoutImpl &gt;',['../classtorch_1_1nn_1_1detail_1_1_dropout_impl_base.html',1,'torch::nn::detail']]],
  ['dropoutop',['DropoutOp',['../classcaffe2_1_1_dropout_op.html',1,'caffe2']]],
  ['dropoutoptions',['DropoutOptions',['../structtorch_1_1nn_1_1_dropout_options.html',1,'torch::nn']]],
  ['dummychunkdatareader',['DummyChunkDataReader',['../struct_dummy_chunk_data_reader.html',1,'']]],
  ['dummyclassfortostring',['DummyClassForToString',['../classc10_1_1guts_1_1detail_1_1_dummy_class_for_to_string.html',1,'c10::guts::detail']]],
  ['dummydataset',['DummyDataset',['../struct_dummy_dataset.html',1,'']]],
  ['dummyname',['DummyName',['../classcaffe2_1_1onnx_1_1_dummy_name.html',1,'caffe2::onnx']]],
  ['dummytensordataset',['DummyTensorDataset',['../struct_dummy_tensor_dataset.html',1,'']]],
  ['dynamicdag',['DynamicDAG',['../structtorch_1_1jit_1_1detail_1_1_dynamic_d_a_g.html',1,'torch::jit::detail']]],
  ['dynamichistogram',['DynamicHistogram',['../classdnnlowp_1_1_dynamic_histogram.html',1,'dnnlowp']]],
  ['dynamiclibrary',['DynamicLibrary',['../structtorch_1_1jit_1_1fuser_1_1cpu_1_1_dynamic_library.html',1,'torch::jit::fuser::cpu']]]
];
