var searchData=
[
  ['safedequeueblobsop',['SafeDequeueBlobsOp',['../classcaffe2_1_1_safe_dequeue_blobs_op.html',1,'caffe2']]],
  ['safeenqueueblobsop',['SafeEnqueueBlobsOp',['../classcaffe2_1_1_safe_enqueue_blobs_op.html',1,'caffe2']]],
  ['sametypeasinput',['SameTypeAsInput',['../structcaffe2_1_1_same_type_as_input.html',1,'caffe2']]],
  ['sampleasgradientop',['SampleAsGradientOp',['../classcaffe2_1_1_sample_as_gradient_op.html',1,'caffe2']]],
  ['sampleasop',['SampleAsOp',['../classcaffe2_1_1_sample_as_op.html',1,'caffe2']]],
  ['sampleinterval',['SampleInterval',['../structcaffe2_1_1_sample_interval.html',1,'caffe2']]],
  ['sampler',['Sampler',['../classtorch_1_1data_1_1samplers_1_1_sampler.html',1,'torch::data::samplers']]],
  ['sampler_3c_20batchsize_20_3e',['Sampler&lt; BatchSize &gt;',['../classtorch_1_1data_1_1samplers_1_1_sampler.html',1,'torch::data::samplers']]],
  ['sampler_3c_20std_3a_3avector_3c_20size_5ft_20_3e_20_3e',['Sampler&lt; std::vector&lt; size_t &gt; &gt;',['../classtorch_1_1data_1_1samplers_1_1_sampler.html',1,'torch::data::samplers']]],
  ['sampler_3c_20testindex_20_3e',['Sampler&lt; TestIndex &gt;',['../classtorch_1_1data_1_1samplers_1_1_sampler.html',1,'torch::data::samplers']]],
  ['sampler_3c_3e',['Sampler&lt;&gt;',['../classtorch_1_1data_1_1samplers_1_1_sampler.html',1,'torch::data::samplers']]],
  ['savedvariable',['SavedVariable',['../classtorch_1_1autograd_1_1_saved_variable.html',1,'torch::autograd']]],
  ['saveop',['SaveOp',['../classcaffe2_1_1_save_op.html',1,'caffe2']]],
  ['scalar',['Scalar',['../classc10_1_1_scalar.html',1,'c10']]],
  ['scalar_5fvalue_5ftype',['scalar_value_type',['../structc10_1_1scalar__value__type.html',1,'c10']]],
  ['scalar_5fvalue_5ftype_3c_20complexhalf_20_3e',['scalar_value_type&lt; ComplexHalf &gt;',['../structc10_1_1scalar__value__type_3_01_complex_half_01_4.html',1,'c10']]],
  ['scalar_5fvalue_5ftype_3c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['scalar_value_type&lt; std::complex&lt; T &gt; &gt;',['../structc10_1_1scalar__value__type_3_01std_1_1complex_3_01_t_01_4_01_4.html',1,'c10']]],
  ['scalarattributevalue',['ScalarAttributeValue',['../structtorch_1_1jit_1_1_scalar_attribute_value.html',1,'torch::jit']]],
  ['scaleimpl',['ScaleImpl',['../structcaffe2_1_1math_1_1detail_1_1_scale_impl.html',1,'caffe2::math::detail']]],
  ['scaleimpl_3c_20t_2c_20cpucontext_2c_201_20_3e',['ScaleImpl&lt; T, CPUContext, 1 &gt;',['../structcaffe2_1_1math_1_1detail_1_1_scale_impl_3_01_t_00_01_c_p_u_context_00_011_01_4.html',1,'caffe2::math::detail']]],
  ['scaleop',['ScaleOp',['../classcaffe2_1_1_scale_op.html',1,'caffe2']]],
  ['scatter',['Scatter',['../structtorch_1_1autograd_1_1_scatter.html',1,'torch::autograd']]],
  ['scatterassignop',['ScatterAssignOp',['../classcaffe2_1_1_scatter_assign_op.html',1,'caffe2']]],
  ['scatterweightedsumop',['ScatterWeightedSumOp',['../classcaffe2_1_1_scatter_weighted_sum_op.html',1,'caffe2']]],
  ['schemaparser',['SchemaParser',['../structtorch_1_1jit_1_1script_1_1_schema_parser.html',1,'torch::jit::script']]],
  ['schematypeparser',['SchemaTypeParser',['../structtorch_1_1jit_1_1script_1_1_schema_type_parser.html',1,'torch::jit::script']]],
  ['scope',['Scope',['../structtorch_1_1jit_1_1_scope.html',1,'torch::jit']]],
  ['scopeguardimpl',['ScopeGuardImpl',['../classcaffe2_1_1detail_1_1_scope_guard_impl.html',1,'caffe2::detail']]],
  ['scopeguardimplbase',['ScopeGuardImplBase',['../classcaffe2_1_1detail_1_1_scope_guard_impl_base.html',1,'caffe2::detail']]],
  ['scratchworkspaces',['ScratchWorkspaces',['../structcaffe2_1_1detail_1_1_scratch_workspaces.html',1,'caffe2::detail']]],
  ['seedingfixture',['SeedingFixture',['../structtorch_1_1test_1_1_seeding_fixture.html',1,'torch::test']]],
  ['segmentidstolengthsop',['SegmentIdsToLengthsOp',['../classcaffe2_1_1_segment_ids_to_lengths_op.html',1,'caffe2']]],
  ['segmentidstorangesop',['SegmentIdsToRangesOp',['../classcaffe2_1_1_segment_ids_to_ranges_op.html',1,'caffe2']]],
  ['segmentonehotop',['SegmentOneHotOp',['../classcaffe2_1_1_segment_one_hot_op.html',1,'caffe2']]],
  ['segmentopgetgradient',['SegmentOpGetGradient',['../structcaffe2_1_1_segment_op_get_gradient.html',1,'caffe2']]],
  ['select',['Select',['../structtorch_1_1jit_1_1script_1_1_select.html',1,'torch::jit::script']]],
  ['selectgradientopbase',['SelectGradientOpBase',['../classcaffe2_1_1_select_gradient_op_base.html',1,'caffe2']]],
  ['selectsmoothl1lossgradientop',['SelectSmoothL1LossGradientOp',['../classcaffe2_1_1_select_smooth_l1_loss_gradient_op.html',1,'caffe2']]],
  ['selectsmoothl1lossop',['SelectSmoothL1LossOp',['../classcaffe2_1_1_select_smooth_l1_loss_op.html',1,'caffe2']]],
  ['self',['Self',['../classtorch_1_1jit_1_1script_1_1_self.html',1,'torch::jit::script']]],
  ['selugradientop',['SeluGradientOp',['../classcaffe2_1_1_selu_gradient_op.html',1,'caffe2']]],
  ['seluop',['SeluOp',['../classcaffe2_1_1_selu_op.html',1,'caffe2']]],
  ['send',['Send',['../class_send.html',1,'']]],
  ['sentineliterator',['SentinelIterator',['../structtorch_1_1data_1_1detail_1_1_sentinel_iterator.html',1,'torch::data::detail']]],
  ['sequenced',['Sequenced',['../structtorch_1_1data_1_1_data_loader_base_1_1_sequenced.html',1,'torch::data::DataLoaderBase']]],
  ['sequencemaskop',['SequenceMaskOp',['../classcaffe2_1_1_sequence_mask_op.html',1,'caffe2']]],
  ['sequencer',['Sequencer',['../structtorch_1_1data_1_1detail_1_1sequencers_1_1_sequencer.html',1,'torch::data::detail::sequencers']]],
  ['sequentialimpl',['SequentialImpl',['../classtorch_1_1nn_1_1_sequential_impl.html',1,'torch::nn']]],
  ['sequentialsampler',['SequentialSampler',['../classtorch_1_1data_1_1samplers_1_1_sequential_sampler.html',1,'torch::data::samplers']]],
  ['sequentialtest',['SequentialTest',['../struct_sequential_test.html',1,'']]],
  ['sgd',['SGD',['../classtorch_1_1optim_1_1_s_g_d.html',1,'torch::optim']]],
  ['sgdoptions',['SGDOptions',['../structtorch_1_1optim_1_1_s_g_d_options.html',1,'torch::optim']]],
  ['shapeinfo',['ShapeInfo',['../structcaffe2_1_1_shape_info.html',1,'caffe2']]],
  ['shapeop',['ShapeOp',['../classcaffe2_1_1_shape_op.html',1,'caffe2']]],
  ['shapeparams',['ShapeParams',['../structcaffe2_1_1lc__op__util_1_1_shape_params.html',1,'caffe2::lc_op_util']]],
  ['sharedbatchdataset',['SharedBatchDataset',['../classtorch_1_1data_1_1datasets_1_1_shared_batch_dataset.html',1,'torch::data::datasets']]],
  ['sharedparserdata',['SharedParserData',['../structtorch_1_1jit_1_1script_1_1_shared_parser_data.html',1,'torch::jit::script']]],
  ['sharedtensorvectorptrdeserializer',['SharedTensorVectorPtrDeserializer',['../classcaffe2_1_1dataset__ops_1_1_shared_tensor_vector_ptr_deserializer.html',1,'caffe2::dataset_ops']]],
  ['sharedtensorvectorptrserializer',['SharedTensorVectorPtrSerializer',['../classcaffe2_1_1dataset__ops_1_1_shared_tensor_vector_ptr_serializer.html',1,'caffe2::dataset_ops']]],
  ['sherwood_5fv3_5fentry',['sherwood_v3_entry',['../structska_1_1detailv3_1_1sherwood__v3__entry.html',1,'ska::detailv3']]],
  ['sherwood_5fv3_5ftable',['sherwood_v3_table',['../classska_1_1detailv3_1_1sherwood__v3__table.html',1,'ska::detailv3']]],
  ['sherwood_5fv3_5ftable_3c_20std_3a_3apair_3c_20k_2c_20v_20_3e_2c_20k_2c_20h_2c_20detailv3_3a_3akeyorvaluehasher_3c_20k_2c_20std_3a_3apair_3c_20k_2c_20v_20_3e_2c_20h_20_3e_2c_20e_2c_20detailv3_3a_3akeyorvalueequality_3c_20k_2c_20std_3a_3apair_3c_20k_2c_20v_20_3e_2c_20e_20_3e_2c_20a_2c_20std_3a_3aallocator_5ftraits_3c_20a_20_3e_3a_3atemplate_20rebind_5falloc_3c_20detailv3_3a_3asherwood_5fv3_5fentry_3c_20std_3a_3apair_3c_20k_2c_20v_20_3e_20_3e_20_3e_20_3e',['sherwood_v3_table&lt; std::pair&lt; K, V &gt;, K, H, detailv3::KeyOrValueHasher&lt; K, std::pair&lt; K, V &gt;, H &gt;, E, detailv3::KeyOrValueEquality&lt; K, std::pair&lt; K, V &gt;, E &gt;, A, std::allocator_traits&lt; A &gt;::template rebind_alloc&lt; detailv3::sherwood_v3_entry&lt; std::pair&lt; K, V &gt; &gt; &gt; &gt;',['../classska_1_1detailv3_1_1sherwood__v3__table.html',1,'ska::detailv3']]],
  ['sherwood_5fv3_5ftable_3c_20t_2c_20t_2c_20h_2c_20detailv3_3a_3afunctor_5fstorage_3c_20uint64_5ft_2c_20h_20_3e_2c_20e_2c_20detailv3_3a_3afunctor_5fstorage_3c_20bool_2c_20e_20_3e_2c_20a_2c_20std_3a_3aallocator_5ftraits_3c_20a_20_3e_3a_3atemplate_20rebind_5falloc_3c_20detailv3_3a_3asherwood_5fv3_5fentry_3c_20t_20_3e_20_3e_20_3e',['sherwood_v3_table&lt; T, T, H, detailv3::functor_storage&lt; uint64_t, H &gt;, E, detailv3::functor_storage&lt; bool, E &gt;, A, std::allocator_traits&lt; A &gt;::template rebind_alloc&lt; detailv3::sherwood_v3_entry&lt; T &gt; &gt; &gt;',['../classska_1_1detailv3_1_1sherwood__v3__table.html',1,'ska::detailv3']]],
  ['sigmoid',['Sigmoid',['../classdnnlowp_1_1_sigmoid.html',1,'dnnlowp']]],
  ['sigmoidcrossentropylossgradientop',['SigmoidCrossEntropyLossGradientOp',['../classcaffe2_1_1_sigmoid_cross_entropy_loss_gradient_op.html',1,'caffe2']]],
  ['sigmoidcrossentropylossop',['SigmoidCrossEntropyLossOp',['../classcaffe2_1_1_sigmoid_cross_entropy_loss_op.html',1,'caffe2']]],
  ['sigmoidcrossentropywithlogitsgradientop',['SigmoidCrossEntropyWithLogitsGradientOp',['../classcaffe2_1_1_sigmoid_cross_entropy_with_logits_gradient_op.html',1,'caffe2']]],
  ['sigmoidcrossentropywithlogitsop',['SigmoidCrossEntropyWithLogitsOp',['../classcaffe2_1_1_sigmoid_cross_entropy_with_logits_op.html',1,'caffe2']]],
  ['sigmoidfocallossgradientop',['SigmoidFocalLossGradientOp',['../classcaffe2_1_1_sigmoid_focal_loss_gradient_op.html',1,'caffe2']]],
  ['sigmoidfocallossop',['SigmoidFocalLossOp',['../classcaffe2_1_1_sigmoid_focal_loss_op.html',1,'caffe2']]],
  ['sigmoidfunctor',['SigmoidFunctor',['../structcaffe2_1_1_sigmoid_functor.html',1,'caffe2']]],
  ['sigmoidgradientfunctor',['SigmoidGradientFunctor',['../structcaffe2_1_1_sigmoid_gradient_functor.html',1,'caffe2']]],
  ['signalhandler',['SignalHandler',['../classcaffe2_1_1_signal_handler.html',1,'caffe2']]],
  ['signaltest',['SignalTest',['../class_signal_test.html',1,'']]],
  ['signfunctor',['SignFunctor',['../structcaffe2_1_1_sign_functor.html',1,'caffe2']]],
  ['simplearray',['SimpleArray',['../structcaffe2_1_1_simple_array.html',1,'caffe2']]],
  ['simplecontainer',['SimpleContainer',['../classtorch_1_1test_1_1_simple_container.html',1,'torch::test']]],
  ['simplenet',['SimpleNet',['../classcaffe2_1_1_simple_net.html',1,'caffe2']]],
  ['simplequeue',['SimpleQueue',['../classcaffe2_1_1_simple_queue.html',1,'caffe2']]],
  ['simplequeue_3c_20caffe2_3a_3aoptask_20_3e',['SimpleQueue&lt; caffe2::OpTask &gt;',['../classcaffe2_1_1_simple_queue.html',1,'caffe2']]],
  ['simplerefcountnet',['SimpleRefCountNet',['../classcaffe2_1_1_simple_ref_count_net.html',1,'caffe2']]],
  ['simplevalue',['SimpleValue',['../structtorch_1_1jit_1_1script_1_1_simple_value.html',1,'torch::jit::script']]],
  ['simplify_5ftype',['simplify_type',['../structsimplify__type.html',1,'']]],
  ['simplify_5ftype_3c_20const_20from_20_3e',['simplify_type&lt; const From &gt;',['../structsimplify__type_3_01const_01_from_01_4.html',1,'']]],
  ['sinfunctor',['SinFunctor',['../structcaffe2_1_1_sin_functor.html',1,'caffe2']]],
  ['singleelementtype',['SingleElementType',['../structc10_1_1_single_element_type.html',1,'c10']]],
  ['singleelementtype_3c_20typekind_3a_3afuturetype_2c_20futuretype_20_3e',['SingleElementType&lt; TypeKind::FutureType, FutureType &gt;',['../structc10_1_1_single_element_type.html',1,'c10']]],
  ['singleelementtype_3c_20typekind_3a_3alisttype_2c_20listtype_20_3e',['SingleElementType&lt; TypeKind::ListType, ListType &gt;',['../structc10_1_1_single_element_type.html',1,'c10']]],
  ['singleelementtype_3c_20typekind_3a_3aoptionaltype_2c_20optionaltype_20_3e',['SingleElementType&lt; TypeKind::OptionalType, OptionalType &gt;',['../structc10_1_1_single_element_type.html',1,'c10']]],
  ['singleloadednetsupplier',['SingleLoadedNetSupplier',['../classcaffe2_1_1emulator_1_1_single_loaded_net_supplier.html',1,'caffe2::emulator']]],
  ['singlenetsupplier',['SingleNetSupplier',['../classcaffe2_1_1emulator_1_1_single_net_supplier.html',1,'caffe2::emulator']]],
  ['singleoptransform',['SingleOpTransform',['../classcaffe2_1_1_single_op_transform.html',1,'caffe2']]],
  ['singradientfunctor',['SinGradientFunctor',['../structcaffe2_1_1_sin_gradient_functor.html',1,'caffe2']]],
  ['sinhfunctor',['SinhFunctor',['../structcaffe2_1_1_sinh_functor.html',1,'caffe2']]],
  ['sinhgradientfunctor',['SinhGradientFunctor',['../structcaffe2_1_1_sinh_gradient_functor.html',1,'caffe2']]],
  ['sinusoidpositionencodingop',['SinusoidPositionEncodingOp',['../classcaffe2_1_1_sinusoid_position_encoding_op.html',1,'caffe2']]],
  ['size',['size',['../structc10_1_1guts_1_1typelist_1_1size.html',1,'c10::guts::typelist']]],
  ['size_3c_20typelist_3c_20types_2e_2e_2e_20_3e_20_3e',['size&lt; typelist&lt; Types... &gt; &gt;',['../structc10_1_1guts_1_1typelist_1_1size_3_01typelist_3_01_types_8_8_8_01_4_01_4.html',1,'c10::guts::typelist']]],
  ['sizeop',['SizeOp',['../classcaffe2_1_1_size_op.html',1,'caffe2']]],
  ['sizerimpl',['SizerImpl',['../unionc10_1_1detail_1_1_sizer_impl.html',1,'c10::detail']]],
  ['skipindices',['SkipIndices',['../classcaffe2_1_1_skip_indices.html',1,'caffe2']]],
  ['skipindices_3c_3e',['SkipIndices&lt;&gt;',['../classcaffe2_1_1_skip_indices_3_4.html',1,'caffe2']]],
  ['sliceexpr',['SliceExpr',['../structtorch_1_1jit_1_1script_1_1_slice_expr.html',1,'torch::jit::script']]],
  ['slicegradientop',['SliceGradientOp',['../classcaffe2_1_1_slice_gradient_op.html',1,'caffe2']]],
  ['sliceop',['SliceOp',['../classcaffe2_1_1_slice_op.html',1,'caffe2']]],
  ['sliceop_3c_20cpucontext_20_3e',['SliceOp&lt; CPUContext &gt;',['../classcaffe2_1_1_slice_op.html',1,'caffe2']]],
  ['smallvector',['SmallVector',['../classc10_1_1_small_vector.html',1,'c10']]],
  ['smallvector_3c_20at_3a_3aoperandinfo_2c_204_20_3e',['SmallVector&lt; at::OperandInfo, 4 &gt;',['../classc10_1_1_small_vector.html',1,'c10']]],
  ['smallvector_3c_20int64_5ft_2c_205_20_3e',['SmallVector&lt; int64_t, 5 &gt;',['../classc10_1_1_small_vector.html',1,'c10']]],
  ['smallvectorbase',['SmallVectorBase',['../classc10_1_1_small_vector_base.html',1,'c10']]],
  ['smallvectorimpl',['SmallVectorImpl',['../classc10_1_1_small_vector_impl.html',1,'c10']]],
  ['smallvectorimpl_3c_20at_3a_3aoperandinfo_20_3e',['SmallVectorImpl&lt; at::OperandInfo &gt;',['../classc10_1_1_small_vector_impl.html',1,'c10']]],
  ['smallvectorimpl_3c_20int64_5ft_20_3e',['SmallVectorImpl&lt; int64_t &gt;',['../classc10_1_1_small_vector_impl.html',1,'c10']]],
  ['smallvectorstorage',['SmallVectorStorage',['../structc10_1_1_small_vector_storage.html',1,'c10']]],
  ['smallvectorstorage_3c_20at_3a_3aoperandinfo_2c_20n_20_3e',['SmallVectorStorage&lt; at::OperandInfo, N &gt;',['../structc10_1_1_small_vector_storage.html',1,'c10']]],
  ['smallvectorstorage_3c_20int64_5ft_2c_20n_20_3e',['SmallVectorStorage&lt; int64_t, N &gt;',['../structc10_1_1_small_vector_storage.html',1,'c10']]],
  ['smallvectorstorage_3c_20t_2c_200_20_3e',['SmallVectorStorage&lt; T, 0 &gt;',['../structc10_1_1_small_vector_storage_3_01_t_00_010_01_4.html',1,'c10']]],
  ['smallvectorstorage_3c_20t_2c_201_20_3e',['SmallVectorStorage&lt; T, 1 &gt;',['../structc10_1_1_small_vector_storage_3_01_t_00_011_01_4.html',1,'c10']]],
  ['smallvectortemplatebase',['SmallVectorTemplateBase',['../classc10_1_1_small_vector_template_base.html',1,'c10']]],
  ['smallvectortemplatebase_3c_20at_3a_3aoperandinfo_2c_20c10_5fis_5ftrivially_5fcopyable_28at_3a_3aoperandinfo_29_3e',['SmallVectorTemplateBase&lt; at::OperandInfo, C10_IS_TRIVIALLY_COPYABLE(at::OperandInfo)&gt;',['../classc10_1_1_small_vector_template_base.html',1,'c10']]],
  ['smallvectortemplatebase_3c_20int64_5ft_2c_20c10_5fis_5ftrivially_5fcopyable_28int64_5ft_29_3e',['SmallVectorTemplateBase&lt; int64_t, C10_IS_TRIVIALLY_COPYABLE(int64_t)&gt;',['../classc10_1_1_small_vector_template_base.html',1,'c10']]],
  ['smallvectortemplatebase_3c_20t_2c_20c10_5fis_5ftrivially_5fcopyable_28t_29_3e',['SmallVectorTemplateBase&lt; T, C10_IS_TRIVIALLY_COPYABLE(T)&gt;',['../classc10_1_1_small_vector_template_base.html',1,'c10']]],
  ['smallvectortemplatebase_3c_20t_2c_20true_20_3e',['SmallVectorTemplateBase&lt; T, true &gt;',['../classc10_1_1_small_vector_template_base_3_01_t_00_01true_01_4.html',1,'c10']]],
  ['smallvectortemplatecommon',['SmallVectorTemplateCommon',['../classc10_1_1_small_vector_template_common.html',1,'c10']]],
  ['smallvectortemplatecommon_3c_20at_3a_3aoperandinfo_20_3e',['SmallVectorTemplateCommon&lt; at::OperandInfo &gt;',['../classc10_1_1_small_vector_template_common.html',1,'c10']]],
  ['smallvectortemplatecommon_3c_20int64_5ft_20_3e',['SmallVectorTemplateCommon&lt; int64_t &gt;',['../classc10_1_1_small_vector_template_common.html',1,'c10']]],
  ['smallvectortemplatecommon_3c_20t_20_3e',['SmallVectorTemplateCommon&lt; T &gt;',['../classc10_1_1_small_vector_template_common.html',1,'c10']]],
  ['smarttensorprinter',['SmartTensorPrinter',['../classcaffe2_1_1_smart_tensor_printer.html',1,'caffe2']]],
  ['smoothl1lossgradientop',['SmoothL1LossGradientOp',['../classcaffe2_1_1_smooth_l1_loss_gradient_op.html',1,'caffe2']]],
  ['smoothl1lossop',['SmoothL1LossOp',['../classcaffe2_1_1_smooth_l1_loss_op.html',1,'caffe2']]],
  ['snpecontext',['SNPEContext',['../struct_s_n_p_e_context.html',1,'']]],
  ['snpeop',['SNPEOp',['../classcaffe2_1_1_s_n_p_e_op.html',1,'caffe2']]],
  ['socket',['Socket',['../class_socket.html',1,'']]],
  ['softmax',['Softmax',['../class_softmax.html',1,'']]],
  ['softmaxfocallossgradientop',['SoftmaxFocalLossGradientOp',['../classcaffe2_1_1_softmax_focal_loss_gradient_op.html',1,'caffe2']]],
  ['softmaxfocallossop',['SoftmaxFocalLossOp',['../classcaffe2_1_1_softmax_focal_loss_op.html',1,'caffe2']]],
  ['softmaxgradientop',['SoftmaxGradientOp',['../classcaffe2_1_1_softmax_gradient_op.html',1,'caffe2']]],
  ['softmaxop',['SoftmaxOp',['../classcaffe2_1_1_softmax_op.html',1,'caffe2']]],
  ['softmaxwithlossgradientop',['SoftmaxWithLossGradientOp',['../classcaffe2_1_1_softmax_with_loss_gradient_op.html',1,'caffe2']]],
  ['softmaxwithlossop',['SoftmaxWithLossOp',['../classcaffe2_1_1_softmax_with_loss_op.html',1,'caffe2']]],
  ['softplusgradientop',['SoftplusGradientOp',['../classcaffe2_1_1_softplus_gradient_op.html',1,'caffe2']]],
  ['softplusop',['SoftplusOp',['../classcaffe2_1_1_softplus_op.html',1,'caffe2']]],
  ['softsignfunctor',['SoftsignFunctor',['../structcaffe2_1_1_softsign_functor.html',1,'caffe2']]],
  ['softsigngradientfunctor',['SoftsignGradientFunctor',['../structcaffe2_1_1_softsign_gradient_functor.html',1,'caffe2']]],
  ['sourceimporter',['SourceImporter',['../structtorch_1_1jit_1_1script_1_1_source_importer.html',1,'torch::jit::script']]],
  ['sourcelocation',['SourceLocation',['../structc10_1_1_source_location.html',1,'c10']]],
  ['sourcelocation',['SourceLocation',['../structtorch_1_1jit_1_1_source_location.html',1,'torch::jit']]],
  ['sourcerange',['SourceRange',['../structtorch_1_1jit_1_1_source_range.html',1,'torch::jit']]],
  ['sourcerangefactory',['SourceRangeFactory',['../structtorch_1_1jit_1_1script_1_1_source_range_factory.html',1,'torch::jit::script']]],
  ['spacebatchopbase',['SpaceBatchOpBase',['../classcaffe2_1_1_space_batch_op_base.html',1,'caffe2']]],
  ['spacetobatchop',['SpaceToBatchOp',['../classcaffe2_1_1_space_to_batch_op.html',1,'caffe2']]],
  ['sparseadadeltaop',['SparseAdadeltaOp',['../classcaffe2_1_1_sparse_adadelta_op.html',1,'caffe2']]],
  ['sparseadagradop',['SparseAdagradOp',['../classcaffe2_1_1_sparse_adagrad_op.html',1,'caffe2']]],
  ['sparseadamop',['SparseAdamOp',['../classcaffe2_1_1_sparse_adam_op.html',1,'caffe2']]],
  ['sparseftrlop',['SparseFtrlOp',['../classcaffe2_1_1_sparse_ftrl_op.html',1,'caffe2']]],
  ['sparsefunhashgradientop',['SparseFunHashGradientOp',['../classcaffe2_1_1_sparse_fun_hash_gradient_op.html',1,'caffe2']]],
  ['sparsefunhashop',['SparseFunHashOp',['../classcaffe2_1_1_sparse_fun_hash_op.html',1,'caffe2']]],
  ['sparselengths8bitsrowwiseop',['SparseLengths8BitsRowwiseOp',['../classcaffe2_1_1_sparse_lengths8_bits_rowwise_op.html',1,'caffe2']]],
  ['sparselengthsfused8bitrowwiseop',['SparseLengthsFused8BitRowwiseOp',['../classcaffe2_1_1_sparse_lengths_fused8_bit_rowwise_op.html',1,'caffe2']]],
  ['sparsematrixreshapeop',['SparseMatrixReshapeOp',['../classcaffe2_1_1_sparse_matrix_reshape_op.html',1,'caffe2']]],
  ['sparsemomentumsgdupdateop',['SparseMomentumSGDUpdateOp',['../classcaffe2_1_1_sparse_momentum_s_g_d_update_op.html',1,'caffe2']]],
  ['sparsenormalizeop',['SparseNormalizeOp',['../classcaffe2_1_1_sparse_normalize_op.html',1,'caffe2']]],
  ['sparsetensorimpl',['SparseTensorImpl',['../structat_1_1_sparse_tensor_impl.html',1,'at']]],
  ['sparsetensorref',['SparseTensorRef',['../structat_1_1_sparse_tensor_ref.html',1,'at']]],
  ['sparsetodensemaskbase',['SparseToDenseMaskBase',['../classcaffe2_1_1_sparse_to_dense_mask_base.html',1,'caffe2']]],
  ['sparsetodensemaskgradientop',['SparseToDenseMaskGradientOp',['../classcaffe2_1_1_sparse_to_dense_mask_gradient_op.html',1,'caffe2']]],
  ['sparsetodensemaskop',['SparseToDenseMaskOp',['../classcaffe2_1_1_sparse_to_dense_mask_op.html',1,'caffe2']]],
  ['sparsetodenseop',['SparseToDenseOp',['../classcaffe2_1_1_sparse_to_dense_op.html',1,'caffe2']]],
  ['sparsewngradop',['SparseWngradOp',['../classcaffe2_1_1_sparse_wngrad_op.html',1,'caffe2']]],
  ['spatialbndnnlowpop',['SpatialBNDNNLowPOp',['../classcaffe2_1_1_spatial_b_n_d_n_n_low_p_op.html',1,'caffe2']]],
  ['spatialbngradientop',['SpatialBNGradientOp',['../classcaffe2_1_1_spatial_b_n_gradient_op.html',1,'caffe2']]],
  ['spatialbnop',['SpatialBNOp',['../classcaffe2_1_1_spatial_b_n_op.html',1,'caffe2']]],
  ['spatialnarrowasgradient',['SpatialNarrowAsGradient',['../classcaffe2_1_1_spatial_narrow_as_gradient.html',1,'caffe2']]],
  ['spatialnarrowasgradientop',['SpatialNarrowAsGradientOp',['../classcaffe2_1_1_spatial_narrow_as_gradient_op.html',1,'caffe2']]],
  ['spatialnarrowasop',['SpatialNarrowAsOp',['../classcaffe2_1_1_spatial_narrow_as_op.html',1,'caffe2']]],
  ['spatialsoftmaxwithlossgradientop',['SpatialSoftmaxWithLossGradientOp',['../classcaffe2_1_1_spatial_softmax_with_loss_gradient_op.html',1,'caffe2']]],
  ['spatialsoftmaxwithlossop',['SpatialSoftmaxWithLossOp',['../classcaffe2_1_1_spatial_softmax_with_loss_op.html',1,'caffe2']]],
  ['spatialtransformerdescriptor',['SpatialTransformerDescriptor',['../structat_1_1native_1_1_spatial_transformer_descriptor.html',1,'at::native']]],
  ['splitbylengthsop',['SplitByLengthsOp',['../classcaffe2_1_1_split_by_lengths_op.html',1,'caffe2']]],
  ['splitop',['SplitOp',['../classcaffe2_1_1_split_op.html',1,'caffe2']]],
  ['splituntil32bit',['SplitUntil32Bit',['../structat_1_1_split_until32_bit.html',1,'at']]],
  ['sqrfunctor',['SqrFunctor',['../structcaffe2_1_1_sqr_functor.html',1,'caffe2']]],
  ['sqrtfunctor',['SqrtFunctor',['../structcaffe2_1_1_sqrt_functor.html',1,'caffe2']]],
  ['squaredl2distancegradientop',['SquaredL2DistanceGradientOp',['../classcaffe2_1_1_squared_l2_distance_gradient_op.html',1,'caffe2']]],
  ['squaredl2distanceop',['SquaredL2DistanceOp',['../classcaffe2_1_1_squared_l2_distance_op.html',1,'caffe2']]],
  ['squarerootdivideop',['SquareRootDivideOp',['../classcaffe2_1_1_square_root_divide_op.html',1,'caffe2']]],
  ['squeezeop',['SqueezeOp',['../classcaffe2_1_1_squeeze_op.html',1,'caffe2']]],
  ['stack',['Stack',['../structtorch_1_1data_1_1transforms_1_1_stack.html',1,'torch::data::transforms']]],
  ['stack_3c_20example_3c_3e_20_3e',['Stack&lt; Example&lt;&gt; &gt;',['../structtorch_1_1data_1_1transforms_1_1_stack_3_01_example_3_4_01_4.html',1,'torch::data::transforms']]],
  ['stack_3c_20tensorexample_20_3e',['Stack&lt; TensorExample &gt;',['../structtorch_1_1data_1_1transforms_1_1_stack_3_01_tensor_example_01_4.html',1,'torch::data::transforms']]],
  ['starred',['Starred',['../structtorch_1_1jit_1_1script_1_1_starred.html',1,'torch::jit::script']]],
  ['stat',['Stat',['../structcaffe2_1_1_stat.html',1,'caffe2']]],
  ['statefuldataloader',['StatefulDataLoader',['../classtorch_1_1data_1_1_stateful_data_loader.html',1,'torch::data']]],
  ['statefuldataset',['StatefulDataset',['../classtorch_1_1data_1_1datasets_1_1_stateful_dataset.html',1,'torch::data::datasets']]],
  ['statefuldataset_3c_20chunkdataset_3c_20chunkreader_2c_20chunksampler_2c_20examplesampler_20_3e_2c_20chunkreader_3a_3abatchtype_2c_20size_5ft_20_3e',['StatefulDataset&lt; ChunkDataset&lt; ChunkReader, ChunkSampler, ExampleSampler &gt;, ChunkReader::BatchType, size_t &gt;',['../classtorch_1_1data_1_1datasets_1_1_stateful_dataset.html',1,'torch::data::datasets']]],
  ['statelessdataloader',['StatelessDataLoader',['../classtorch_1_1data_1_1_stateless_data_loader.html',1,'torch::data']]],
  ['staticlinkingprotector',['StaticLinkingProtector',['../structcaffe2_1_1_static_linking_protector.html',1,'caffe2']]],
  ['staticstat',['StaticStat',['../classcaffe2_1_1_static_stat.html',1,'caffe2']]],
  ['statregistry',['StatRegistry',['../classcaffe2_1_1_stat_registry.html',1,'caffe2']]],
  ['statregistrycreateop',['StatRegistryCreateOp',['../classcaffe2_1_1_stat_registry_create_op.html',1,'caffe2']]],
  ['statregistryexportop',['StatRegistryExportOp',['../classcaffe2_1_1_stat_registry_export_op.html',1,'caffe2']]],
  ['statregistryupdateop',['StatRegistryUpdateOp',['../classcaffe2_1_1_stat_registry_update_op.html',1,'caffe2']]],
  ['statvalue',['StatValue',['../classcaffe2_1_1_stat_value.html',1,'caffe2']]],
  ['stddevexportedstat',['StdDevExportedStat',['../classcaffe2_1_1_std_dev_exported_stat.html',1,'caffe2']]],
  ['stdoutputformatter',['StdOutputFormatter',['../classcaffe2_1_1emulator_1_1_std_output_formatter.html',1,'caffe2::emulator']]],
  ['steplearningrate',['StepLearningRate',['../classcaffe2_1_1_step_learning_rate.html',1,'caffe2']]],
  ['stmt',['Stmt',['../structtorch_1_1jit_1_1script_1_1_stmt.html',1,'torch::jit::script']]],
  ['stopgradientop',['StopGradientOp',['../classcaffe2_1_1_stop_gradient_op.html',1,'caffe2']]],
  ['stoponsignal',['StopOnSignal',['../structcaffe2_1_1_stop_on_signal.html',1,'caffe2']]],
  ['storage',['Storage',['../structc10_1_1_storage.html',1,'c10']]],
  ['storage_5ft',['storage_t',['../unionc10_1_1storage__t.html',1,'c10']]],
  ['storageimpl',['StorageImpl',['../structc10_1_1_storage_impl.html',1,'c10']]],
  ['storagetype',['StorageType',['../class_storage_type.html',1,'']]],
  ['storagetype_3c_20u_2e_2e_2e_20_3e',['StorageType&lt; U... &gt;',['../class_storage_type.html',1,'']]],
  ['storagetype_3c_3e',['StorageType&lt;&gt;',['../class_storage_type_3_4.html',1,'']]],
  ['storeaddop',['StoreAddOp',['../classcaffe2_1_1_store_add_op.html',1,'caffe2']]],
  ['storegetop',['StoreGetOp',['../classcaffe2_1_1_store_get_op.html',1,'caffe2']]],
  ['storehandler',['StoreHandler',['../classcaffe2_1_1_store_handler.html',1,'caffe2']]],
  ['storehandlernotavailableexception',['StoreHandlerNotAvailableException',['../structcaffe2_1_1_store_handler_not_available_exception.html',1,'caffe2']]],
  ['storehandlertimeoutexception',['StoreHandlerTimeoutException',['../structcaffe2_1_1_store_handler_timeout_exception.html',1,'caffe2']]],
  ['storesetop',['StoreSetOp',['../classcaffe2_1_1_store_set_op.html',1,'caffe2']]],
  ['storewaitop',['StoreWaitOp',['../classcaffe2_1_1_store_wait_op.html',1,'caffe2']]],
  ['stream',['Stream',['../structat_1_1native_1_1_stream.html',1,'at::native']]],
  ['stream',['Stream',['../classc10_1_1_stream.html',1,'c10']]],
  ['streamguard',['StreamGuard',['../structc10_1_1_stream_guard.html',1,'c10']]],
  ['streamsampler',['StreamSampler',['../classtorch_1_1data_1_1samplers_1_1_stream_sampler.html',1,'torch::data::samplers']]],
  ['strided_5ftensor_5fiter',['strided_tensor_iter',['../structat_1_1strided__tensor__iter.html',1,'at']]],
  ['strided_5ftensor_5fiter_5ffixed',['strided_tensor_iter_fixed',['../structat_1_1strided__tensor__iter__fixed.html',1,'at']]],
  ['strideddata',['StridedData',['../structtorch_1_1utils_1_1_strided_data.html',1,'torch::utils']]],
  ['string',['String',['../structtorch_1_1jit_1_1script_1_1_string.html',1,'torch::jit::script']]],
  ['stringdeserializer',['StringDeserializer',['../classcaffe2_1_1_string_deserializer.html',1,'caffe2']]],
  ['stringjoinop',['StringJoinOp',['../classcaffe2_1_1_string_join_op.html',1,'caffe2']]],
  ['stringliteral',['StringLiteral',['../structtorch_1_1jit_1_1script_1_1_string_literal.html',1,'torch::jit::script']]],
  ['stringprovider',['StringProvider',['../structcaffe2_1_1_string_provider.html',1,'caffe2']]],
  ['stringserializer',['StringSerializer',['../classcaffe2_1_1_string_serializer.html',1,'caffe2']]],
  ['stringsourcelocation',['StringSourceLocation',['../structtorch_1_1jit_1_1_string_source_location.html',1,'torch::jit']]],
  ['stringtype',['StringType',['../structc10_1_1_string_type.html',1,'c10']]],
  ['strip_5fclass',['strip_class',['../structc10_1_1guts_1_1detail_1_1strip__class.html',1,'c10::guts::detail']]],
  ['strip_5fclass_3c_20result_28class_3a_3a_2a_29_28args_2e_2e_2e_29_20const_20_20_3e',['strip_class&lt; Result(Class::*)(Args...) const  &gt;',['../structc10_1_1guts_1_1detail_1_1strip__class_3_01_result_07_class_1_1_5_08_07_args_8_8_8_08_01const_01_01_4.html',1,'c10::guts::detail']]],
  ['strip_5fclass_3c_20result_28class_3a_3a_2a_29_28args_2e_2e_2e_29_3e',['strip_class&lt; Result(Class::*)(Args...)&gt;',['../structc10_1_1guts_1_1detail_1_1strip__class_3_01_result_07_class_1_1_5_08_07_args_8_8_8_08_4.html',1,'c10::guts::detail']]],
  ['stumpfuncindexop',['StumpFuncIndexOp',['../classcaffe2_1_1_stump_func_index_op.html',1,'caffe2']]],
  ['stumpfuncop',['StumpFuncOp',['../classcaffe2_1_1_stump_func_op.html',1,'caffe2']]],
  ['subfunctor',['SubFunctor',['../structcaffe2_1_1_sub_functor.html',1,'caffe2']]],
  ['subgraph',['Subgraph',['../classnom_1_1_subgraph.html',1,'nom']]],
  ['subgraph_3c_20t_2c_20u_2e_2e_2e_20_3e',['Subgraph&lt; T, U... &gt;',['../classnom_1_1_subgraph.html',1,'nom']]],
  ['subgraphmatchresult',['SubgraphMatchResult',['../classnom_1_1matcher_1_1_subgraph_match_result.html',1,'nom::matcher']]],
  ['subscript',['Subscript',['../structtorch_1_1jit_1_1script_1_1_subscript.html',1,'torch::jit::script']]],
  ['sugaredvalue',['SugaredValue',['../structtorch_1_1jit_1_1script_1_1_sugared_value.html',1,'torch::jit::script']]],
  ['sum',['Sum',['../class_sum.html',1,'']]],
  ['sumdnnlowpop',['SumDNNLowPOp',['../classcaffe2_1_1_sum_d_n_n_low_p_op.html',1,'caffe2']]],
  ['sumelementsgradientop',['SumElementsGradientOp',['../classcaffe2_1_1_sum_elements_gradient_op.html',1,'caffe2']]],
  ['sumelementsintop',['SumElementsIntOp',['../classcaffe2_1_1_sum_elements_int_op.html',1,'caffe2']]],
  ['sumelementsop',['SumElementsOp',['../classcaffe2_1_1_sum_elements_op.html',1,'caffe2']]],
  ['summarizeop',['SummarizeOp',['../classcaffe2_1_1_summarize_op.html',1,'caffe2']]],
  ['sumop',['SumOp',['../classcaffe2_1_1_sum_op.html',1,'caffe2']]],
  ['sumrangereducer',['SumRangeReducer',['../classcaffe2_1_1_sum_range_reducer.html',1,'caffe2']]],
  ['sumrangereducer_3c_20t_2c_20cpucontext_20_3e',['SumRangeReducer&lt; T, CPUContext &gt;',['../classcaffe2_1_1_sum_range_reducer_3_01_t_00_01_c_p_u_context_01_4.html',1,'caffe2']]],
  ['sumrangereducerdef',['SumRangeReducerDef',['../structcaffe2_1_1_sum_range_reducer_def.html',1,'caffe2']]],
  ['sumrangereducergradient',['SumRangeReducerGradient',['../classcaffe2_1_1_sum_range_reducer_gradient.html',1,'caffe2']]],
  ['sumreducedimsgradientop',['SumReduceDimsGradientOp',['../classcaffe2_1_1_sum_reduce_dims_gradient_op.html',1,'caffe2']]],
  ['sumreducedimsop',['SumReduceDimsOp',['../classcaffe2_1_1_sum_reduce_dims_op.html',1,'caffe2']]],
  ['sumreducelikeop',['SumReduceLikeOp',['../classcaffe2_1_1_sum_reduce_like_op.html',1,'caffe2']]],
  ['sumreducer',['SumReducer',['../structcaffe2_1_1_sum_reducer.html',1,'caffe2']]],
  ['sumreducer_3c_20t_2c_20cpucontext_20_3e',['SumReducer&lt; T, CPUContext &gt;',['../classcaffe2_1_1_sum_reducer_3_01_t_00_01_c_p_u_context_01_4.html',1,'caffe2']]],
  ['sumreducerdef',['SumReducerDef',['../structcaffe2_1_1_sum_reducer_def.html',1,'caffe2']]],
  ['sumreducergradient',['SumReducerGradient',['../classcaffe2_1_1_sum_reducer_gradient.html',1,'caffe2']]],
  ['sumrelu',['SumRelu',['../class_sum_relu.html',1,'']]],
  ['sumreluop',['SumReluOp',['../classcaffe2_1_1_sum_relu_op.html',1,'caffe2']]],
  ['sumsqrelementsop',['SumSqrElementsOp',['../classcaffe2_1_1_sum_sqr_elements_op.html',1,'caffe2']]],
  ['suspend',['Suspend',['../structtorch_1_1jit_1_1_suspend.html',1,'torch::jit']]],
  ['swishfunctor',['SwishFunctor',['../structcaffe2_1_1_swish_functor.html',1,'caffe2']]],
  ['swishgradientop',['SwishGradientOp',['../classcaffe2_1_1_swish_gradient_op.html',1,'caffe2']]],
  ['symbol',['Symbol',['../structc10_1_1_symbol.html',1,'c10']]],
  ['symbolic_5funconvertible',['symbolic_unconvertible',['../structtorch_1_1autograd_1_1symbolic__unconvertible.html',1,'torch::autograd']]],
  ['symboliccontext',['SymbolicContext',['../structtorch_1_1autograd_1_1_symbolic_context.html',1,'torch::autograd']]],
  ['symbolicvariable',['SymbolicVariable',['../structtorch_1_1jit_1_1_symbolic_variable.html',1,'torch::jit']]],
  ['syncedcudnnstate',['SyncedCuDNNState',['../structcaffe2_1_1_cu_d_n_n_wrapper_1_1_synced_cu_d_n_n_state.html',1,'caffe2::CuDNNWrapper']]],
  ['syncedmiopenstate',['SyncedMIOPENState',['../structcaffe2_1_1_m_i_o_p_e_n_wrapper_1_1_synced_m_i_o_p_e_n_state.html',1,'caffe2::MIOPENWrapper']]]
];
