var searchData=
[
  ['observable',['Observable',['../classcaffe2_1_1_observable.html',1,'caffe2']]],
  ['observable_3c_20netbase_20_3e',['Observable&lt; NetBase &gt;',['../classcaffe2_1_1_observable.html',1,'caffe2']]],
  ['observable_3c_20operatorbase_20_3e',['Observable&lt; OperatorBase &gt;',['../classcaffe2_1_1_observable.html',1,'caffe2']]],
  ['observerbase',['ObserverBase',['../classcaffe2_1_1_observer_base.html',1,'caffe2']]],
  ['observerbase_3c_20netbase_20_3e',['ObserverBase&lt; NetBase &gt;',['../classcaffe2_1_1_observer_base.html',1,'caffe2']]],
  ['observerbase_3c_20operatorbase_20_3e',['ObserverBase&lt; OperatorBase &gt;',['../classcaffe2_1_1_observer_base.html',1,'caffe2']]],
  ['observerconfig',['ObserverConfig',['../classcaffe2_1_1_observer_config.html',1,'caffe2']]],
  ['offsetalias',['OffsetAlias',['../structcaffe2_1_1detail_1_1_offset_alias.html',1,'caffe2::detail']]],
  ['onehotop',['OneHotOp',['../classcaffe2_1_1_one_hot_op.html',1,'caffe2']]],
  ['onnxannotation',['OnnxAnnotation',['../class_onnx_annotation.html',1,'']]],
  ['onnxattributes',['OnnxAttributes',['../classcaffe2_1_1onnx_1_1_onnx_attributes.html',1,'caffe2::onnx']]],
  ['onnxbackendgraphmap',['OnnxBackendGraphMap',['../classcaffe2_1_1onnx_1_1_onnx_backend_graph_map.html',1,'caffe2::onnx']]],
  ['onnxexporter',['OnnxExporter',['../classcaffe2_1_1onnx_1_1_onnx_exporter.html',1,'caffe2::onnx']]],
  ['onnxifiop',['OnnxifiOp',['../classcaffe2_1_1_onnxifi_op.html',1,'caffe2']]],
  ['onnxifitransformer',['OnnxifiTransformer',['../classcaffe2_1_1_onnxifi_transformer.html',1,'caffe2']]],
  ['onnxifitransformeroptions',['OnnxifiTransformerOptions',['../structcaffe2_1_1_onnxifi_transformer_options.html',1,'caffe2']]],
  ['onnxnode',['OnnxNode',['../structcaffe2_1_1onnx_1_1_onnx_node.html',1,'caffe2::onnx']]],
  ['onnxwhileop',['ONNXWhileOp',['../classcaffe2_1_1_o_n_n_x_while_op.html',1,'caffe2']]],
  ['operandinfo',['OperandInfo',['../structat_1_1_operand_info.html',1,'at']]],
  ['operator',['Operator',['../structtorch_1_1jit_1_1_operator.html',1,'torch::jit']]],
  ['operator',['Operator',['../classcaffe2_1_1_operator.html',1,'caffe2']]],
  ['operator_3c_20cpucontext_20_3e',['Operator&lt; CPUContext &gt;',['../classcaffe2_1_1_operator.html',1,'caffe2']]],
  ['operator_3c_20cudacontext_20_3e',['Operator&lt; CUDAContext &gt;',['../classcaffe2_1_1_operator.html',1,'caffe2']]],
  ['operator_3c_20hipcontext_20_3e',['Operator&lt; HIPContext &gt;',['../classcaffe2_1_1_operator.html',1,'caffe2']]],
  ['operator_3c_20ideepcontext_20_3e',['Operator&lt; IDEEPContext &gt;',['../classcaffe2_1_1_operator.html',1,'caffe2']]],
  ['operatorattachingnetobserver',['OperatorAttachingNetObserver',['../classcaffe2_1_1_operator_attaching_net_observer.html',1,'caffe2']]],
  ['operatorattachingnetobserver_3c_20profileoperatorobserver_2c_20profileobserver_20_3e',['OperatorAttachingNetObserver&lt; ProfileOperatorObserver, ProfileObserver &gt;',['../classcaffe2_1_1_operator_attaching_net_observer.html',1,'caffe2']]],
  ['operatorattachingnetobserver_3c_20runcountoperatorobserver_2c_20runcountnetobserver_20_3e',['OperatorAttachingNetObserver&lt; RunCountOperatorObserver, RunCountNetObserver &gt;',['../classcaffe2_1_1_operator_attaching_net_observer.html',1,'caffe2']]],
  ['operatorattachingnetobserver_3c_20timeoperatorobserver_2c_20timeobserver_20_3e',['OperatorAttachingNetObserver&lt; TimeOperatorObserver, TimeObserver &gt;',['../classcaffe2_1_1_operator_attaching_net_observer.html',1,'caffe2']]],
  ['operatorbase',['OperatorBase',['../classcaffe2_1_1_operator_base.html',1,'caffe2']]],
  ['operatorhandle',['OperatorHandle',['../classc10_1_1_operator_handle.html',1,'c10']]],
  ['operatorinfo',['OperatorInfo',['../structcaffe2_1_1_output_min_max_observer_1_1_operator_info.html',1,'caffe2::OutputMinMaxObserver']]],
  ['operatornode',['OperatorNode',['../structcaffe2_1_1dag__utils_1_1_operator_node.html',1,'caffe2::dag_utils']]],
  ['operatorset',['OperatorSet',['../structtorch_1_1jit_1_1_operator_set.html',1,'torch::jit']]],
  ['opgraphnode',['OpGraphNode',['../structcaffe2_1_1dag__utils_1_1_op_graph_node.html',1,'caffe2::dag_utils']]],
  ['opkernel',['OpKernel',['../classc10_1_1_op_kernel.html',1,'c10']]],
  ['opregistrationlistener',['OpRegistrationListener',['../classc10_1_1_op_registration_listener.html',1,'c10']]],
  ['opschema',['OpSchema',['../classcaffe2_1_1_op_schema.html',1,'caffe2']]],
  ['opschemaregistrar',['OpSchemaRegistrar',['../classc10_1_1detail_1_1_op_schema_registrar.html',1,'c10::detail']]],
  ['opschemaregistry',['OpSchemaRegistry',['../classcaffe2_1_1_op_schema_registry.html',1,'caffe2']]],
  ['opset_5fpytorch_5fver1',['OpSet_PyTorch_ver1',['../class_o_n_n_x___n_a_m_e_s_p_a_c_e_1_1_op_set___py_torch__ver1.html',1,'ONNX_NAMESPACE']]],
  ['opsvalue',['OpsValue',['../structtorch_1_1jit_1_1script_1_1_ops_value.html',1,'torch::jit::script']]],
  ['optask',['OpTask',['../structcaffe2_1_1_op_task.html',1,'caffe2']]],
  ['optimizationpass',['OptimizationPass',['../classcaffe2_1_1_optimization_pass.html',1,'caffe2']]],
  ['optimizer',['Optimizer',['../classtorch_1_1optim_1_1_optimizer.html',1,'torch::optim']]],
  ['optimizerbase',['OptimizerBase',['../classtorch_1_1optim_1_1detail_1_1_optimizer_base.html',1,'torch::optim::detail']]],
  ['optional',['optional',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20batch_20_3e',['optional&lt; Batch &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20batchrequest_20_3e',['optional&lt; BatchRequest &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aaliasinfo_20_3e',['optional&lt; c10::AliasInfo &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinedeviceguard_3c_20c10_3a_3ahip_3a_3ahipguardimplmasqueradingascuda_20_3e_20_3e',['optional&lt; c10::impl::InlineDeviceGuard&lt; c10::hip::HIPGuardImplMasqueradingAsCUDA &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinedeviceguard_3c_20impl_3a_3acudaguardimpl_20_3e_20_3e',['optional&lt; c10::impl::InlineDeviceGuard&lt; impl::CUDAGuardImpl &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinedeviceguard_3c_20impl_3a_3avirtualguardimpl_20_3e_20_3e',['optional&lt; c10::impl::InlineDeviceGuard&lt; impl::VirtualGuardImpl &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinedeviceguard_3c_20t_20_3e_20_3e',['optional&lt; c10::impl::InlineDeviceGuard&lt; T &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinestreamguard_3c_20c10_3a_3ahip_3a_3ahipguardimplmasqueradingascuda_20_3e_20_3e',['optional&lt; c10::impl::InlineStreamGuard&lt; c10::hip::HIPGuardImplMasqueradingAsCUDA &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinestreamguard_3c_20impl_3a_3acudaguardimpl_20_3e_20_3e',['optional&lt; c10::impl::InlineStreamGuard&lt; impl::CUDAGuardImpl &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinestreamguard_3c_20impl_3a_3avirtualguardimpl_20_3e_20_3e',['optional&lt; c10::impl::InlineStreamGuard&lt; impl::VirtualGuardImpl &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aimpl_3a_3ainlinestreamguard_3c_20t_20_3e_20_3e',['optional&lt; c10::impl::InlineStreamGuard&lt; T &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aivalue_20_3e',['optional&lt; c10::IValue &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3aopkernel_20_3e',['optional&lt; c10::OpKernel &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20c10_3a_3atensortypeid_20_3e',['optional&lt; c10::TensorTypeId &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20cudnnmode_20_3e',['optional&lt; CuDNNMode &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20int_20_3e',['optional&lt; int &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20int32_5ft_20_3e',['optional&lt; int32_t &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20int64_5ft_20_3e',['optional&lt; int64_t &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20nom_3a_3arepr_3a_3atensor_20_3e',['optional&lt; nom::repr::Tensor &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20size_5ft_20_3e',['optional&lt; size_t &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20std_3a_3achrono_3a_3amilliseconds_20_3e',['optional&lt; std::chrono::milliseconds &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20std_3a_3astring_20_3e',['optional&lt; std::string &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20std_3a_3avector_3c_20c10_3a_3ac10_3a_3aoptional_3c_20at_3a_3acuda_3a_3acudastream_20_3e_20_3e_20_3e',['optional&lt; std::vector&lt; c10::c10::optional&lt; at::cuda::CUDAStream &gt; &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20std_3a_3avector_3c_20int64_5ft_20_3e_20_3e',['optional&lt; std::vector&lt; int64_t &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20std_3a_3avector_3c_20torch_3a_3ajit_3a_3agraphexecutor_20_2a_20_3e_20_3e',['optional&lt; std::vector&lt; torch::jit::GraphExecutor * &gt; &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20t_20_26_20_3e',['optional&lt; T &amp; &gt;',['../classc10_1_1optional_3_01_t_01_6_01_4.html',1,'c10']]],
  ['optional_3c_20t_20_26_26_20_3e',['optional&lt; T &amp;&amp; &gt;',['../classc10_1_1optional_3_01_t_01_6_6_01_4.html',1,'c10']]],
  ['optional_3c_20torch_3a_3adata_3a_3adataloaderbase_3a_3aquitworker_20_3e',['optional&lt; torch::data::DataLoaderBase::QuitWorker &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20torch_3a_3ajit_3a_3anamedvalue_20_3e',['optional&lt; torch::jit::NamedValue &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20torch_3a_3ajit_3a_3asourcerange_20_3e',['optional&lt; torch::jit::SourceRange &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_3c_20typeptr_20_3e',['optional&lt; TypePtr &gt;',['../classc10_1_1optional.html',1,'c10']]],
  ['optional_5fbase',['optional_base',['../structc10_1_1optional__base.html',1,'c10']]],
  ['optionalcudaguard',['OptionalCUDAGuard',['../structc10_1_1cuda_1_1_optional_c_u_d_a_guard.html',1,'c10::cuda']]],
  ['optionalcudastreamguard',['OptionalCUDAStreamGuard',['../structc10_1_1cuda_1_1_optional_c_u_d_a_stream_guard.html',1,'c10::cuda']]],
  ['optionaldeviceguard',['OptionalDeviceGuard',['../classc10_1_1_optional_device_guard.html',1,'c10']]],
  ['optionalhipguardmasqueradingascuda',['OptionalHIPGuardMasqueradingAsCUDA',['../structc10_1_1hip_1_1_optional_h_i_p_guard_masquerading_as_c_u_d_a.html',1,'c10::hip']]],
  ['optionalhipstreamguardmasqueradingascuda',['OptionalHIPStreamGuardMasqueradingAsCUDA',['../structc10_1_1hip_1_1_optional_h_i_p_stream_guard_masquerading_as_c_u_d_a.html',1,'c10::hip']]],
  ['optionalstreamguard',['OptionalStreamGuard',['../structc10_1_1_optional_stream_guard.html',1,'c10']]],
  ['optionaltype',['OptionalType',['../structc10_1_1_optional_type.html',1,'c10']]],
  ['opwrapper',['OpWrapper',['../classcaffe2_1_1_op_wrapper.html',1,'caffe2']]],
  ['ordereddict',['OrderedDict',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['ordereddict_3c_20std_3a_3astring_2c_20at_3a_3atensor_20_3e',['OrderedDict&lt; std::string, at::Tensor &gt;',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['ordereddict_3c_20std_3a_3astring_2c_20std_3a_3ashared_5fptr_3c_20torch_3a_3ann_3a_3amodule_20_3e_20_3e',['OrderedDict&lt; std::string, std::shared_ptr&lt; torch::nn::Module &gt; &gt;',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['ordereddict_3c_20std_3a_3astring_2c_20std_3a_3aunique_5fptr_3c_20torch_3a_3ajit_3a_3ascript_3a_3amethod_20_3e_20_3e',['OrderedDict&lt; std::string, std::unique_ptr&lt; torch::jit::script::Method &gt; &gt;',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['ordereddict_3c_20std_3a_3astring_2c_20torch_3a_3ajit_3a_3ascript_3a_3anamedivalue_20_3e',['OrderedDict&lt; std::string, torch::jit::script::NamedIValue &gt;',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['ordereddict_3c_20std_3a_3astring_2c_20torch_3a_3ajit_3a_3ascript_3a_3anamedmodule_20_3e',['OrderedDict&lt; std::string, torch::jit::script::NamedModule &gt;',['../classtorch_1_1_ordered_dict.html',1,'torch']]],
  ['orderedsequencer',['OrderedSequencer',['../structtorch_1_1data_1_1detail_1_1sequencers_1_1_ordered_sequencer.html',1,'torch::data::detail::sequencers']]],
  ['outputarchive',['OutputArchive',['../classtorch_1_1serialize_1_1_output_archive.html',1,'torch::serialize']]],
  ['outputformatter',['OutputFormatter',['../classcaffe2_1_1emulator_1_1_output_formatter.html',1,'caffe2::emulator']]],
  ['outputmapandsize',['OutputMapAndSize',['../structtorch_1_1jit_1_1fuser_1_1_output_map_and_size.html',1,'torch::jit::fuser']]],
  ['outputminmaxnetobserver',['OutputMinMaxNetObserver',['../classcaffe2_1_1_output_min_max_net_observer.html',1,'caffe2']]],
  ['outputminmaxobserver',['OutputMinMaxObserver',['../classcaffe2_1_1_output_min_max_observer.html',1,'caffe2']]],
  ['overloadedfunctionvalue',['OverloadedFunctionValue',['../structtorch_1_1jit_1_1script_1_1_overloaded_function_value.html',1,'torch::jit::script']]]
];
