var searchData=
[
  ['raise',['Raise',['../structtorch_1_1jit_1_1script_1_1_raise.html',1,'torch::jit::script']]],
  ['randomsampler',['RandomSampler',['../classtorch_1_1data_1_1samplers_1_1_random_sampler.html',1,'torch::data::samplers']]],
  ['range',['Range',['../structat_1_1_range.html',1,'at']]],
  ['rangeeventlist',['RangeEventList',['../structtorch_1_1autograd_1_1profiler_1_1_range_event_list.html',1,'torch::autograd::profiler']]],
  ['rangefillop',['RangeFillOp',['../classcaffe2_1_1_range_fill_op.html',1,'caffe2']]],
  ['rangeop',['RangeOp',['../classcaffe2_1_1_range_op.html',1,'caffe2']]],
  ['readadapterinterface',['ReadAdapterInterface',['../classcaffe2_1_1serialize_1_1_read_adapter_interface.html',1,'caffe2::serialize']]],
  ['readyqueue',['ReadyQueue',['../structtorch_1_1autograd_1_1_ready_queue.html',1,'torch::autograd']]],
  ['rebatchingqueue',['RebatchingQueue',['../classcaffe2_1_1_rebatching_queue.html',1,'caffe2']]],
  ['receive',['Receive',['../class_receive.html',1,'']]],
  ['reciprocalfunctor',['ReciprocalFunctor',['../structcaffe2_1_1_reciprocal_functor.html',1,'caffe2']]],
  ['reciprocalgradientfunctor',['ReciprocalGradientFunctor',['../structcaffe2_1_1_reciprocal_gradient_functor.html',1,'caffe2']]],
  ['recordfunction',['RecordFunction',['../structtorch_1_1autograd_1_1profiler_1_1_record_function.html',1,'torch::autograd::profiler']]],
  ['recordprofile',['RecordProfile',['../structtorch_1_1autograd_1_1profiler_1_1_record_profile.html',1,'torch::autograd::profiler']]],
  ['recurrentbaseop',['RecurrentBaseOp',['../classcaffe2_1_1_recurrent_base_op.html',1,'caffe2']]],
  ['recurrentgradient',['RecurrentGradient',['../structcaffe2_1_1detail_1_1_recurrent_gradient.html',1,'caffe2::detail']]],
  ['recurrentgradientop',['RecurrentGradientOp',['../classcaffe2_1_1_recurrent_gradient_op.html',1,'caffe2']]],
  ['recurrentinput',['RecurrentInput',['../structcaffe2_1_1detail_1_1_recurrent_input.html',1,'caffe2::detail']]],
  ['recurrentnetworkblobfetcherop',['RecurrentNetworkBlobFetcherOp',['../classcaffe2_1_1_recurrent_network_blob_fetcher_op.html',1,'caffe2']]],
  ['recurrentnetworkexecutorbase',['RecurrentNetworkExecutorBase',['../classcaffe2_1_1_recurrent_network_executor_base.html',1,'caffe2']]],
  ['recurrentnetworkgradientop',['RecurrentNetworkGradientOp',['../classcaffe2_1_1_recurrent_network_gradient_op.html',1,'caffe2']]],
  ['recurrentnetworkop',['RecurrentNetworkOp',['../classcaffe2_1_1_recurrent_network_op.html',1,'caffe2']]],
  ['recurrentop',['RecurrentOp',['../classcaffe2_1_1_recurrent_op.html',1,'caffe2']]],
  ['recurrentparamaccessop',['RecurrentParamAccessOp',['../classcaffe2_1_1_recurrent_param_access_op.html',1,'caffe2']]],
  ['recursivemethodcallerror',['RecursiveMethodCallError',['../structtorch_1_1jit_1_1script_1_1_recursive_method_call_error.html',1,'torch::jit::script']]],
  ['redisstorehandler',['RedisStoreHandler',['../classcaffe2_1_1_redis_store_handler.html',1,'caffe2']]],
  ['redisstorehandlercreateop',['RedisStoreHandlerCreateOp',['../classcaffe2_1_1_redis_store_handler_create_op.html',1,'caffe2']]],
  ['reducegradientop',['ReduceGradientOp',['../classcaffe2_1_1_reduce_gradient_op.html',1,'caffe2']]],
  ['reducenccltest',['ReduceNCCLTest',['../class_reduce_n_c_c_l_test.html',1,'']]],
  ['reduceop',['ReduceOp',['../classcaffe2_1_1_reduce_op.html',1,'caffe2']]],
  ['reducetailsumop',['ReduceTailSumOp',['../classcaffe2_1_1_reduce_tail_sum_op.html',1,'caffe2']]],
  ['refinements',['Refinements',['../structtorch_1_1jit_1_1script_1_1_refinements.html',1,'torch::jit::script']]],
  ['registerer',['Registerer',['../classc10_1_1_registerer.html',1,'c10']]],
  ['registerfusionbackend',['RegisterFusionBackend',['../structtorch_1_1jit_1_1fuser_1_1_register_fusion_backend.html',1,'torch::jit::fuser']]],
  ['registeroperators',['RegisterOperators',['../structtorch_1_1jit_1_1_register_operators.html',1,'torch::jit']]],
  ['registerquantizationparamsnetobserver',['RegisterQuantizationParamsNetObserver',['../classcaffe2_1_1_register_quantization_params_net_observer.html',1,'caffe2']]],
  ['registerquantizationparamswithhistogramnetobserver',['RegisterQuantizationParamsWithHistogramNetObserver',['../classcaffe2_1_1_register_quantization_params_with_histogram_net_observer.html',1,'caffe2']]],
  ['registrar',['Registrar',['../structcaffe2_1_1_blob_stat_registry_1_1_registrar.html',1,'caffe2::BlobStatRegistry']]],
  ['registrationlistenerlist',['RegistrationListenerList',['../classc10_1_1detail_1_1_registration_listener_list.html',1,'c10::detail']]],
  ['registry',['Registry',['../classc10_1_1_registry.html',1,'c10']]],
  ['relu',['Relu',['../class_relu.html',1,'']]],
  ['reludnnlowpop',['ReluDNNLowPOp',['../classcaffe2_1_1_relu_d_n_n_low_p_op.html',1,'caffe2']]],
  ['relufunctor',['ReluFunctor',['../structcaffe2_1_1_relu_functor.html',1,'caffe2']]],
  ['relugradientfunctor',['ReluGradientFunctor',['../structcaffe2_1_1_relu_gradient_functor.html',1,'caffe2']]],
  ['relunfunctor',['ReluNFunctor',['../structcaffe2_1_1_relu_n_functor.html',1,'caffe2']]],
  ['relungradientfunctor',['ReluNGradientFunctor',['../structcaffe2_1_1_relu_n_gradient_functor.html',1,'caffe2']]],
  ['removedatablocksop',['RemoveDataBlocksOp',['../classcaffe2_1_1_remove_data_blocks_op.html',1,'caffe2']]],
  ['removepaddingop',['RemovePaddingOp',['../classcaffe2_1_1_remove_padding_op.html',1,'caffe2']]],
  ['replacenanop',['ReplaceNaNOp',['../classcaffe2_1_1_replace_na_n_op.html',1,'caffe2']]],
  ['resetcounterop',['ResetCounterOp',['../classcaffe2_1_1_reset_counter_op.html',1,'caffe2']]],
  ['reshape',['Reshape',['../class_reshape.html',1,'']]],
  ['reshapeop',['ReshapeOp',['../classcaffe2_1_1_reshape_op.html',1,'caffe2']]],
  ['reshapeop_3c_20uint8_5ft_2c_20cpucontext_20_3e',['ReshapeOp&lt; uint8_t, CPUContext &gt;',['../classcaffe2_1_1_reshape_op.html',1,'caffe2']]],
  ['resizelikeop',['ResizeLikeOp',['../classcaffe2_1_1_resize_like_op.html',1,'caffe2']]],
  ['resizenearestdnnlowpop',['ResizeNearestDNNLowPOp',['../classcaffe2_1_1_resize_nearest_d_n_n_low_p_op.html',1,'caffe2']]],
  ['resizenearestgradientop',['ResizeNearestGradientOp',['../classcaffe2_1_1_resize_nearest_gradient_op.html',1,'caffe2']]],
  ['resizenearestop',['ResizeNearestOp',['../classcaffe2_1_1_resize_nearest_op.html',1,'caffe2']]],
  ['resourceguard',['ResourceGuard',['../classtorch_1_1jit_1_1_resource_guard.html',1,'torch::jit']]],
  ['result',['Result',['../structtorch_1_1data_1_1_data_loader_base_1_1_result.html',1,'torch::data::DataLoaderBase']]],
  ['result',['Result',['../structnom_1_1algorithm_1_1_topo_sort_1_1_result.html',1,'nom::algorithm::TopoSort']]],
  ['retrievecountop',['RetrieveCountOp',['../classcaffe2_1_1_retrieve_count_op.html',1,'caffe2']]],
  ['return',['Return',['../structtorch_1_1jit_1_1script_1_1_return.html',1,'torch::jit::script']]],
  ['return',['Return',['../classnom_1_1repr_1_1_return.html',1,'nom::repr']]],
  ['return_5ftype_5fof_5fforward_5fimpl',['return_type_of_forward_impl',['../structtorch_1_1detail_1_1return__type__of__forward__impl.html',1,'torch::detail']]],
  ['return_5ftype_5fof_5fforward_5fimpl',['return_type_of_forward_impl',['../structreturn__type__of__forward__impl.html',1,'']]],
  ['return_5ftype_5fof_5fforward_5fimpl_3c_20false_2c_20c_2c_20args_2e_2e_2e_20_3e',['return_type_of_forward_impl&lt; false, C, Args... &gt;',['../structreturn__type__of__forward__impl_3_01false_00_01_c_00_01_args_8_8_8_01_4.html',1,'']]],
  ['return_5ftype_5fof_5fforward_5fimpl_3c_20false_2c_20c_2c_20args_2e_2e_2e_20_3e',['return_type_of_forward_impl&lt; false, C, Args... &gt;',['../structtorch_1_1detail_1_1return__type__of__forward__impl_3_01false_00_01_c_00_01_args_8_8_8_01_4.html',1,'torch::detail']]],
  ['return_5ftype_5fof_5fforward_5fimpl_3c_20true_2c_20c_2c_20args_2e_2e_2e_20_3e',['return_type_of_forward_impl&lt; true, C, Args... &gt;',['../structreturn__type__of__forward__impl_3_01true_00_01_c_00_01_args_8_8_8_01_4.html',1,'']]],
  ['return_5ftype_5fof_5fforward_5fimpl_3c_20true_2c_20c_2c_20args_2e_2e_2e_20_3e',['return_type_of_forward_impl&lt; true, C, Args... &gt;',['../structtorch_1_1detail_1_1return__type__of__forward__impl_3_01true_00_01_c_00_01_args_8_8_8_01_4.html',1,'torch::detail']]],
  ['returninfo',['ReturnInfo',['../structtorch_1_1jit_1_1script_1_1_return_info.html',1,'torch::jit::script']]],
  ['reverse',['reverse',['../structc10_1_1guts_1_1typelist_1_1reverse.html',1,'c10::guts::typelist']]],
  ['reverse_3c_20typelist_3c_20head_2c_20tail_2e_2e_2e_20_3e_20_3e',['reverse&lt; typelist&lt; Head, Tail... &gt; &gt;',['../structc10_1_1guts_1_1typelist_1_1reverse_3_01typelist_3_01_head_00_01_tail_8_8_8_01_4_01_4.html',1,'c10::guts::typelist']]],
  ['reverse_3c_20typelist_3c_3e_20_3e',['reverse&lt; typelist&lt;&gt; &gt;',['../structc10_1_1guts_1_1typelist_1_1reverse_3_01typelist_3_4_01_4.html',1,'c10::guts::typelist']]],
  ['reversedetails',['ReverseDetails',['../structtorch_1_1jit_1_1_reverse_details.html',1,'torch::jit']]],
  ['reversepackedsegsop',['ReversePackedSegsOp',['../classcaffe2_1_1_reverse_packed_segs_op.html',1,'caffe2']]],
  ['rmacregionsop',['RMACRegionsOp',['../classcaffe2_1_1_r_m_a_c_regions_op.html',1,'caffe2']]],
  ['rmsprop',['RMSprop',['../classtorch_1_1optim_1_1_r_m_sprop.html',1,'torch::optim']]],
  ['rmspropop',['RmsPropOp',['../classcaffe2_1_1_rms_prop_op.html',1,'caffe2']]],
  ['rmspropoptions',['RMSpropOptions',['../structtorch_1_1optim_1_1_r_m_sprop_options.html',1,'torch::optim']]],
  ['rnnapplylinkop',['RNNApplyLinkOp',['../classcaffe2_1_1_r_n_n_apply_link_op.html',1,'caffe2']]],
  ['rnndescriptor',['RNNDescriptor',['../structat_1_1native_1_1_r_n_n_descriptor.html',1,'at::native']]],
  ['rnnimpl',['RNNImpl',['../classtorch_1_1nn_1_1_r_n_n_impl.html',1,'torch::nn']]],
  ['rnnimplbase',['RNNImplBase',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html',1,'torch::nn::detail']]],
  ['rnnimplbase_3c_20gruimpl_20_3e',['RNNImplBase&lt; GRUImpl &gt;',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html',1,'torch::nn::detail']]],
  ['rnnimplbase_3c_20lstmimpl_20_3e',['RNNImplBase&lt; LSTMImpl &gt;',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html',1,'torch::nn::detail']]],
  ['rnnimplbase_3c_20rnnimpl_20_3e',['RNNImplBase&lt; RNNImpl &gt;',['../classtorch_1_1nn_1_1detail_1_1_r_n_n_impl_base.html',1,'torch::nn::detail']]],
  ['rnnnetoperator',['RNNNetOperator',['../structcaffe2_1_1_r_n_n_net_operator.html',1,'caffe2']]],
  ['rnnoptions',['RNNOptions',['../structtorch_1_1nn_1_1_r_n_n_options.html',1,'torch::nn']]],
  ['rnnoptionsbase',['RNNOptionsBase',['../structtorch_1_1nn_1_1detail_1_1_r_n_n_options_base.html',1,'torch::nn::detail']]],
  ['rnnoutput',['RNNOutput',['../structtorch_1_1nn_1_1_r_n_n_output.html',1,'torch::nn']]],
  ['rnntest',['RNNTest',['../struct_r_n_n_test.html',1,'']]],
  ['rocksdb',['RocksDB',['../classcaffe2_1_1db_1_1_rocks_d_b.html',1,'caffe2::db']]],
  ['rocksdbcursor',['RocksDBCursor',['../classcaffe2_1_1db_1_1_rocks_d_b_cursor.html',1,'caffe2::db']]],
  ['rocksdbtransaction',['RocksDBTransaction',['../classcaffe2_1_1db_1_1_rocks_d_b_transaction.html',1,'caffe2::db']]],
  ['roialigngradientop',['RoIAlignGradientOp',['../classcaffe2_1_1_ro_i_align_gradient_op.html',1,'caffe2']]],
  ['roialignop',['RoIAlignOp',['../classcaffe2_1_1_ro_i_align_op.html',1,'caffe2']]],
  ['roialignrotatedgradientop',['RoIAlignRotatedGradientOp',['../classcaffe2_1_1_ro_i_align_rotated_gradient_op.html',1,'caffe2']]],
  ['roialignrotatedop',['RoIAlignRotatedOp',['../classcaffe2_1_1_ro_i_align_rotated_op.html',1,'caffe2']]],
  ['roipoolfgradientop',['RoIPoolFGradientOp',['../classcaffe2_1_1_ro_i_pool_f_gradient_op.html',1,'caffe2']]],
  ['roipoolfop',['RoIPoolFOp',['../classcaffe2_1_1_ro_i_pool_f_op.html',1,'caffe2']]],
  ['roipoolgradientop',['RoIPoolGradientOp',['../classcaffe2_1_1_ro_i_pool_gradient_op.html',1,'caffe2']]],
  ['roipoolop',['RoIPoolOp',['../classcaffe2_1_1_ro_i_pool_op.html',1,'caffe2']]],
  ['rotatedbox',['RotatedBox',['../structcaffe2_1_1utils_1_1_rotated_box.html',1,'caffe2::utils']]],
  ['rowmulop',['RowMulOp',['../classcaffe2_1_1_row_mul_op.html',1,'caffe2']]],
  ['rowwise8bitquantizedtofloatop',['Rowwise8BitQuantizedToFloatOp',['../classcaffe2_1_1_rowwise8_bit_quantized_to_float_op.html',1,'caffe2']]],
  ['rowwisesparseadagradop',['RowWiseSparseAdagradOp',['../classcaffe2_1_1_row_wise_sparse_adagrad_op.html',1,'caffe2']]],
  ['rowwisesparseadamop',['RowWiseSparseAdamOp',['../classcaffe2_1_1_row_wise_sparse_adam_op.html',1,'caffe2']]],
  ['rsqrtfunctor',['RsqrtFunctor',['../structcaffe2_1_1_rsqrt_functor.html',1,'caffe2']]],
  ['rsqrtgradientfunctor',['RsqrtGradientFunctor',['../structcaffe2_1_1_rsqrt_gradient_functor.html',1,'caffe2']]],
  ['runcountnetobserver',['RunCountNetObserver',['../classcaffe2_1_1_run_count_net_observer.html',1,'caffe2']]],
  ['runcountoperatorobserver',['RunCountOperatorObserver',['../classcaffe2_1_1_run_count_operator_observer.html',1,'caffe2']]],
  ['runnablenet',['RunnableNet',['../structcaffe2_1_1emulator_1_1_runnable_net.html',1,'caffe2::emulator']]]
];
