var searchData=
[
  ['b',['B',['../struct_b.html',1,'']]],
  ['backendgraphinfo',['BackendGraphInfo',['../structcaffe2_1_1onnx_1_1_backend_graph_info.html',1,'caffe2::onnx']]],
  ['backendtransformerbase',['BackendTransformerBase',['../classcaffe2_1_1_backend_transformer_base.html',1,'caffe2']]],
  ['bad_5foptional_5faccess',['bad_optional_access',['../classc10_1_1bad__optional__access.html',1,'c10']]],
  ['bar',['Bar',['../classc10__test_1_1_bar.html',1,'c10_test']]],
  ['barrier',['Barrier',['../struct_barrier.html',1,'']]],
  ['basecontext',['BaseContext',['../classat_1_1_base_context.html',1,'at']]],
  ['baseinputaccessor',['BaseInputAccessor',['../classcaffe2_1_1_base_input_accessor.html',1,'caffe2']]],
  ['basereducer',['BaseReducer',['../classcaffe2_1_1_base_reducer.html',1,'caffe2']]],
  ['basereducergradient',['BaseReducerGradient',['../classcaffe2_1_1_base_reducer_gradient.html',1,'caffe2']]],
  ['basicblock',['BasicBlock',['../classnom_1_1repr_1_1_basic_block.html',1,'nom::repr']]],
  ['batchboxcoxop',['BatchBoxCoxOp',['../classcaffe2_1_1_batch_box_cox_op.html',1,'caffe2']]],
  ['batchbucketizeop',['BatchBucketizeOp',['../classcaffe2_1_1_batch_bucketize_op.html',1,'caffe2']]],
  ['batchbucketonehotop',['BatchBucketOneHotOp',['../classcaffe2_1_1_batch_bucket_one_hot_op.html',1,'caffe2']]],
  ['batchdatabuffer',['BatchDataBuffer',['../classtorch_1_1data_1_1datasets_1_1detail_1_1_batch_data_buffer.html',1,'torch::data::datasets::detail']]],
  ['batchdataset',['BatchDataset',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20chunkdataset_3c_20chunkreader_2c_20chunksampler_2c_20examplesampler_20_3e_2c_20optional_3c_20chunkreader_3a_3abatchtype_20_3e_2c_20size_5ft_20_3e',['BatchDataset&lt; ChunkDataset&lt; ChunkReader, ChunkSampler, ExampleSampler &gt;, optional&lt; ChunkReader::BatchType &gt;, size_t &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dataset_2c_20size_5ft_20_3e',['BatchDataset&lt; Dataset, size_t &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dummydataset_2c_20std_3a_3avector_3c_20int_20_3e_20_3e',['BatchDataset&lt; DummyDataset, std::vector&lt; int &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20dummytensordataset_2c_20std_3a_3avector_3c_20example_3c_20torch_3a_3atensor_2c_20int_20_3e_20_3e_20_3e',['BatchDataset&lt; DummyTensorDataset, std::vector&lt; Example&lt; torch::Tensor, int &gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20mapdataset_3c_20sourcedataset_2c_20appliedtransform_20_3e_2c_20detail_3a_3aoptional_5fif_5ft_3c_20sourcedataset_3a_3ais_5fstateful_2c_20appliedtransform_3a_3aoutputbatchtype_20_3e_2c_20sourcedataset_3a_3abatchrequesttype_20_3e',['BatchDataset&lt; MapDataset&lt; SourceDataset, AppliedTransform &gt;, detail::optional_if_t&lt; SourceDataset::is_stateful, AppliedTransform::OutputBatchType &gt;, SourceDataset::BatchRequestType &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20mnist_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; MNIST, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20self_2c_20optional_3c_20batch_20_3e_2c_20batchrequest_20_3e',['BatchDataset&lt; Self, optional&lt; Batch &gt;, BatchRequest &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20self_2c_20std_3a_3avector_3c_20singleexample_20_3e_20_3e',['BatchDataset&lt; Self, std::vector&lt; SingleExample &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20sharedbatchdataset_3c_20underlyingdataset_20_3e_2c_20underlyingdataset_3a_3abatchtype_2c_20underlyingdataset_3a_3abatchrequesttype_20_3e',['BatchDataset&lt; SharedBatchDataset&lt; UnderlyingDataset &gt;, UnderlyingDataset::BatchType, UnderlyingDataset::BatchRequestType &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20tensordataset_2c_20std_3a_3avector_3c_20tensorexample_20_3e_20_3e',['BatchDataset&lt; TensorDataset, std::vector&lt; TensorExample &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20tensorstringdataset_2c_20std_3a_3avector_3c_20example_3c_20torch_3a_3atensor_2c_20std_3a_3astring_20_3e_20_3e_20_3e',['BatchDataset&lt; TensorStringDataset, std::vector&lt; Example&lt; torch::Tensor, std::string &gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20testindexdataset_2c_20std_3a_3avector_3c_20int_20_3e_2c_20testindex_20_3e',['BatchDataset&lt; TestIndexDataset, std::vector&lt; int &gt;, TestIndex &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20uncopyabledataset_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; UnCopyableDataset, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20uncopyabledataset_2c_20std_3a_3avector_3c_20int_20_3e_20_3e',['BatchDataset&lt; UncopyableDataset, std::vector&lt; int &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdataset_3c_20unsizeddataset_2c_20std_3a_3avector_3c_20example_3c_3e_20_3e_20_3e',['BatchDataset&lt; UnsizedDataset, std::vector&lt; Example&lt;&gt; &gt; &gt;',['../classtorch_1_1data_1_1datasets_1_1_batch_dataset.html',1,'torch::data::datasets']]],
  ['batchdensetosparseop',['BatchDenseToSparseOp',['../classcaffe2_1_1_batch_dense_to_sparse_op.html',1,'caffe2']]],
  ['batchgathergradientop',['BatchGatherGradientOp',['../classcaffe2_1_1_batch_gather_gradient_op.html',1,'caffe2']]],
  ['batchgatherop',['BatchGatherOp',['../classcaffe2_1_1_batch_gather_op.html',1,'caffe2']]],
  ['batchlambda',['BatchLambda',['../classtorch_1_1data_1_1transforms_1_1_batch_lambda.html',1,'torch::data::transforms']]],
  ['batchmatmuldnnlowpop',['BatchMatMulDNNLowPOp',['../classcaffe2_1_1_batch_mat_mul_d_n_n_low_p_op.html',1,'caffe2']]],
  ['batchmatmulop',['BatchMatMulOp',['../classcaffe2_1_1_batch_mat_mul_op.html',1,'caffe2']]],
  ['batchmomentsgradientop',['BatchMomentsGradientOp',['../classcaffe2_1_1_batch_moments_gradient_op.html',1,'caffe2']]],
  ['batchmomentsop',['BatchMomentsOp',['../classcaffe2_1_1_batch_moments_op.html',1,'caffe2']]],
  ['batchnormalization',['BatchNormalization',['../class_batch_normalization.html',1,'']]],
  ['batchnormimpl',['BatchNormImpl',['../classtorch_1_1nn_1_1_batch_norm_impl.html',1,'torch::nn']]],
  ['batchnormoptions',['BatchNormOptions',['../structtorch_1_1nn_1_1_batch_norm_options.html',1,'torch::nn']]],
  ['batchonehotop',['BatchOneHotOp',['../classcaffe2_1_1_batch_one_hot_op.html',1,'caffe2']]],
  ['batchpermutationdnnlowpop',['BatchPermutationDNNLowPOp',['../classcaffe2_1_1_batch_permutation_d_n_n_low_p_op.html',1,'caffe2']]],
  ['batchpermutationgradientop',['BatchPermutationGradientOp',['../classcaffe2_1_1_batch_permutation_gradient_op.html',1,'caffe2']]],
  ['batchpermutationop',['BatchPermutationOp',['../classcaffe2_1_1_batch_permutation_op.html',1,'caffe2']]],
  ['batchsize',['BatchSize',['../structtorch_1_1data_1_1samplers_1_1_batch_size.html',1,'torch::data::samplers']]],
  ['batchsparsetodenseop',['BatchSparseToDenseOp',['../classcaffe2_1_1_batch_sparse_to_dense_op.html',1,'caffe2']]],
  ['batchtensor',['BatchTensor',['../structtorch_1_1jit_1_1_batch_tensor.html',1,'torch::jit']]],
  ['batchtospaceop',['BatchToSpaceOp',['../classcaffe2_1_1_batch_to_space_op.html',1,'caffe2']]],
  ['batchtransform',['BatchTransform',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20input_2c_20output_20_3e',['BatchTransform&lt; Input, Output &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20std_3a_3avector_3c_20example_3c_20tensor_2c_20target_20_3e_20_3e_2c_20std_3a_3avector_3c_20example_3c_20tensor_2c_20target_20_3e_20_3e_20_3e',['BatchTransform&lt; std::vector&lt; Example&lt; Tensor, Target &gt; &gt;, std::vector&lt; Example&lt; Tensor, Target &gt; &gt; &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['batchtransform_3c_20std_3a_3avector_3c_20input_20_3e_2c_20std_3a_3avector_3c_20output_20_3e_20_3e',['BatchTransform&lt; std::vector&lt; Input &gt;, std::vector&lt; Output &gt; &gt;',['../classtorch_1_1data_1_1transforms_1_1_batch_transform.html',1,'torch::data::transforms']]],
  ['bboxtransformop',['BBoxTransformOp',['../classcaffe2_1_1_b_box_transform_op.html',1,'caffe2']]],
  ['benchmarkparam',['BenchmarkParam',['../structcaffe2_1_1emulator_1_1_benchmark_param.html',1,'caffe2::emulator']]],
  ['benchmarkrunner',['BenchmarkRunner',['../classcaffe2_1_1emulator_1_1_benchmark_runner.html',1,'caffe2::emulator']]],
  ['bernoullijsdgradientop',['BernoulliJSDGradientOp',['../classcaffe2_1_1_bernoulli_j_s_d_gradient_op.html',1,'caffe2']]],
  ['bernoullijsdop',['BernoulliJSDOp',['../classcaffe2_1_1_bernoulli_j_s_d_op.html',1,'caffe2']]],
  ['binary_5ffunction_5ftraits',['binary_function_traits',['../structbinary__function__traits.html',1,'']]],
  ['binaryelementwisednnlowpop',['BinaryElementwiseDNNLowPOp',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisednnlowpop_3c_20t_2c_20addfp32op_20_3e',['BinaryElementwiseDNNLowPOp&lt; T, AddFp32Op &gt;',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisednnlowpop_3c_20t_2c_20mulfp32op_20_3e',['BinaryElementwiseDNNLowPOp&lt; T, MulFp32Op &gt;',['../classcaffe2_1_1_binary_elementwise_d_n_n_low_p_op.html',1,'caffe2']]],
  ['binaryelementwisewithargsgradientop',['BinaryElementwiseWithArgsGradientOp',['../classcaffe2_1_1_binary_elementwise_with_args_gradient_op.html',1,'caffe2']]],
  ['binaryelementwisewithargsgradientop_3c_20numerictypes_2c_20cpucontext_2c_20binaryfunctorwithdefaultctor_3c_20divfunctor_3c_20cpucontext_20_3e_20_3e_2c_20sametypeasinput_2c_20sametypeasinput_20_3e',['BinaryElementwiseWithArgsGradientOp&lt; NumericTypes, CPUContext, BinaryFunctorWithDefaultCtor&lt; DivFunctor&lt; CPUContext &gt; &gt;, SameTypeAsInput, SameTypeAsInput &gt;',['../classcaffe2_1_1_binary_elementwise_with_args_gradient_op_3_01_numeric_types_00_01_c_p_u_context_18719035c30b9048fc92376cf087945e.html',1,'caffe2']]],
  ['binaryelementwisewithargsop',['BinaryElementwiseWithArgsOp',['../classcaffe2_1_1_binary_elementwise_with_args_op.html',1,'caffe2']]],
  ['binaryfunctorwithdefaultctor',['BinaryFunctorWithDefaultCtor',['../structcaffe2_1_1_binary_functor_with_default_ctor.html',1,'caffe2']]],
  ['binaryfunctorwithdefaultctor_3c_20caffe2_3a_3adivfunctor_3c_20caffe2_3a_3acpucontext_20_3e_20_3e',['BinaryFunctorWithDefaultCtor&lt; caffe2::DivFunctor&lt; caffe2::CPUContext &gt; &gt;',['../structcaffe2_1_1_binary_functor_with_default_ctor.html',1,'caffe2']]],
  ['binop',['BinOp',['../structtorch_1_1jit_1_1script_1_1_bin_op.html',1,'torch::jit::script']]],
  ['bisectpercentileop',['BisectPercentileOp',['../classcaffe2_1_1_bisect_percentile_op.html',1,'caffe2']]],
  ['blob',['Blob',['../classcaffe2_1_1_blob.html',1,'caffe2']]],
  ['blobdeserializerbase',['BlobDeserializerBase',['../classcaffe2_1_1_blob_deserializer_base.html',1,'caffe2']]],
  ['blobserializerbase',['BlobSerializerBase',['../classcaffe2_1_1_blob_serializer_base.html',1,'caffe2']]],
  ['blobsqueue',['BlobsQueue',['../classcaffe2_1_1_blobs_queue.html',1,'caffe2']]],
  ['blobsqueuedb',['BlobsQueueDB',['../classcaffe2_1_1db_1_1_blobs_queue_d_b.html',1,'caffe2::db']]],
  ['blobsqueuedbcursor',['BlobsQueueDBCursor',['../classcaffe2_1_1db_1_1_blobs_queue_d_b_cursor.html',1,'caffe2::db']]],
  ['blobstatgetter',['BlobStatGetter',['../structcaffe2_1_1_blob_stat_getter.html',1,'caffe2']]],
  ['blobstatregistry',['BlobStatRegistry',['../structcaffe2_1_1_blob_stat_registry.html',1,'caffe2']]],
  ['block',['Block',['../structtorch_1_1jit_1_1_block.html',1,'torch::jit']]],
  ['blockingcounter',['BlockingCounter',['../classcaffe2_1_1_blocking_counter.html',1,'caffe2']]],
  ['booleandispatchvalue',['BooleanDispatchValue',['../structtorch_1_1jit_1_1script_1_1_boolean_dispatch_value.html',1,'torch::jit::script']]],
  ['booleanmaskop',['BooleanMaskOp',['../classcaffe2_1_1_boolean_mask_op.html',1,'caffe2']]],
  ['booleanunmaskop',['BooleanUnmaskOp',['../classcaffe2_1_1_boolean_unmask_op.html',1,'caffe2']]],
  ['boolinfo',['BoolInfo',['../structtorch_1_1jit_1_1script_1_1_bool_info.html',1,'torch::jit::script']]],
  ['booltype',['BoolType',['../structc10_1_1_bool_type.html',1,'c10']]],
  ['boundshapeinferencer',['BoundShapeInferencer',['../classcaffe2_1_1_bound_shape_inferencer.html',1,'caffe2']]],
  ['boundshapespec',['BoundShapeSpec',['../structcaffe2_1_1_bound_shape_spec.html',1,'caffe2']]],
  ['boxwithnmslimitop',['BoxWithNMSLimitOp',['../classcaffe2_1_1_box_with_n_m_s_limit_op.html',1,'caffe2']]],
  ['branch',['Branch',['../classnom_1_1repr_1_1_branch.html',1,'nom::repr']]],
  ['brgnchwctopackedint8bgrastylizerdeprocessop',['BRGNCHWCToPackedInt8BGRAStylizerDeprocessOp',['../classcaffe2_1_1_b_r_g_n_c_h_w_c_to_packed_int8_b_g_r_a_stylizer_deprocess_op.html',1,'caffe2']]],
  ['broadcastnccltest',['BroadcastNCCLTest',['../class_broadcast_n_c_c_l_test.html',1,'']]],
  ['bufferedtokenizer',['BufferedTokenizer',['../classcaffe2_1_1_buffered_tokenizer.html',1,'caffe2']]],
  ['buffertestmodule',['BufferTestModule',['../struct_buffer_test_module.html',1,'']]],
  ['builder',['Builder',['../structat_1_1_tensor_iterator_1_1_builder.html',1,'at::TensorIterator']]],
  ['builtinfunction',['BuiltinFunction',['../structtorch_1_1jit_1_1script_1_1_builtin_function.html',1,'torch::jit::script']]],
  ['builtinfunctionregistry',['BuiltinFunctionRegistry',['../structtorch_1_1jit_1_1script_1_1_builtin_function_registry.html',1,'torch::jit::script']]],
  ['builtinmodule',['BuiltinModule',['../structtorch_1_1jit_1_1script_1_1_builtin_module.html',1,'torch::jit::script']]],
  ['byteweightdequantop',['ByteWeightDequantOp',['../classcaffe2_1_1_byte_weight_dequant_op.html',1,'caffe2']]]
];
